import type { GameDefinition } from '../types'

export const sevenWondersDuel: GameDefinition = {
  slug: '7-wonders-duel',
  name: '7 Wonders Duel',
  icon: '⚔️',
  tagline: 'La misma civilización, pero cara a cara',
  theme: { primary: '#8c3b3b' },
  minPlayers: 2,
  maxPlayers: 2,
  playTime: { min: 30, max: 30 },
  difficulty: 'medium',
  scoreLabel: 'Puntos de victoria',
  scoreLabelShort: 'PV',
  totalMode: 'computed',
  winnerRule: 'highest',

  fields: [
    {
      key: 'civilian',
      label: 'Edificios civiles (azules)',
      short: 'Civiles',
      icon: '🏛️',
      type: 'number',
      points: 1,
      min: 0,
      showInSummary: true,
    },
    {
      key: 'wonders',
      label: 'Maravillas construidas',
      short: 'Maravillas',
      icon: '🗿',
      type: 'number',
      points: 1,
      min: 0,
      showInSummary: true,
    },
    {
      key: 'progress',
      label: 'Fichas de progreso',
      short: 'Progreso',
      icon: '📜',
      type: 'number',
      points: 1,
      min: 0,
      showInSummary: true,
    },
    {
      key: 'coin_points',
      label: 'Monedas',
      short: 'Monedas',
      icon: '🪙',
      type: 'number',
      points: 1,
      min: 0,
      hint: 'Divide tus monedas entre 3 y redondea hacia abajo',
    },
    {
      key: 'commercial',
      label: 'Edificios comerciales (amarillos)',
      short: 'Comercio',
      icon: '⚖️',
      type: 'number',
      points: 1,
      min: 0,
    },
    {
      key: 'guilds',
      label: 'Gremios (morados)',
      short: 'Gremios',
      icon: '🟣',
      type: 'number',
      points: 1,
      min: 0,
      showInSummary: true,
    },
    {
      key: 'science',
      label: 'Ciencia (verdes)',
      short: 'Ciencia',
      icon: '🔬',
      type: 'number',
      points: 1,
      min: 0,
    },
    {
      key: 'military',
      label: 'Ventaja militar',
      short: 'Militar',
      icon: '🛡️',
      type: 'number',
      points: 1,
      min: 0,
      showInSummary: true,
      hint: 'Los puntos de la zona donde esté el peón al acabar',
    },
    {
      key: 'supremacy',
      label: 'Ganó por victoria inmediata',
      short: 'Fulminante',
      icon: '💥',
      type: 'toggle',
      group: 'Registro',
      uniquePerMatch: true,
      hint: 'Supremacía militar o científica: la partida acaba en el acto',
    },
  ],

  rules: {
    players: '2 jugadores',
    duration: '30 min',
    setup: [
      'Coloca el tablero central con el peón de conflicto en el 0 y las fichas militares a los lados.',
      'Pon cinco fichas de progreso al azar en el espacio del tablero.',
      'Cada jugador se queda con cuatro maravillas mediante el reparto inicial; el resto se retira.',
      'Cada uno empieza con 7 monedas.',
      'Monta la estructura de cartas de la primera era con su forma de pirámide.',
    ],
    turn: [
      {
        name: '1. Coger una carta accesible',
        detail:
          'Solo puedes coger cartas que no estén tapadas por ninguna otra. Al quitarla, se destapan las de debajo.',
      },
      {
        name: '2. Decidir qué haces con ella',
        detail:
          'Construir el edificio pagando su coste, descartarla para ganar monedas (2 + tus edificios amarillos) o usarla para levantar una maravilla.',
      },
      {
        name: '3. Efectos',
        detail:
          'Los edificios militares mueven el peón hacia tu rival, y algunos progresos y maravillas te dan un turno extra.',
      },
    ],
    scoring: [
      { what: 'Edificios azules', points: 'Sus puntos impresos' },
      { what: 'Maravillas', points: 'Los puntos de cada una' },
      { what: 'Fichas de progreso', points: 'Lo que indiquen' },
      { what: 'Monedas', points: '1 punto por cada 3' },
      { what: 'Amarillos y morados', points: 'Según el texto de la carta' },
      { what: 'Posición del peón militar', points: '0, 2, 5 o 10 puntos' },
      { what: 'Supremacía militar o científica', points: 'Victoria inmediata' },
    ],
    endCondition:
      'La partida acaba tras la tercera era y gana quien más puntos sume; en caso de empate, gana quien tenga más edificios azules. También puede acabar antes: si el peón militar llega a la capital del rival (supremacía militar) o si reúnes seis símbolos científicos distintos (supremacía científica).',
    reminders: [
      'Solo se pueden construir siete maravillas entre los dos: la octava se queda sin levantar.',
      'Los encadenamientos ahorran el coste entero de la carta, incluidas las monedas.',
      'Comprar un recurso al banco cuesta 2 monedas más 1 por cada carta de ese recurso que tenga tu rival.',
      'Al conseguir dos símbolos científicos iguales te llevas una ficha de progreso.',
      'Si no puedes pagar una carta, siempre puedes descartarla por monedas: nunca te quedas sin jugada.',
    ],
    officialLink: {
      label: 'Web oficial (Repos Production)',
      url: 'https://www.rprod.com/',
    },
  },
}
