/**
 * GENERADO AUTOMÁTICAMENTE POR `npm run covers` — NO EDITAR A MANO.
 * Las portadas elegidas a mano van en `scripts/covers.overrides.ts`.
 *
 * Portada de cada juego integrado. El fichero está en `public/covers/` y la ruta es
 * relativa a la base del sitio: úsala siempre con `coverUrl()` de `src/games/covers.ts`,
 * que le pone delante `import.meta.env.BASE_URL` (en GitHub Pages el sitio cuelga de
 * `/mesa/`, así que una ruta absoluta no valdría).
 *
 * Los juegos que no salen aquí no tienen portada conocida y se pintan con su icono.
 *
 * `sourceUrl` es de dónde se sacó la imagen. Las carátulas son de sus editoriales; se
 * guardan a 512 px con fines de identificación (ver la nota del README).
 *
 * Última actualización: 2026-08-14
 * Con portada: 166 de 393
 */
export interface Cover {
  /** Ruta relativa a la base del sitio: `covers/azul.webp`. */
  file: string
  source: 'manual' | 'bgg' | 'wikidata' | 'wikipedia'
  sourceUrl: string
}

export const COVERS: Record<string, Cover> = {
  '7-wonders': { file: 'covers/7-wonders.webp', source: 'wikipedia', sourceUrl: 'https://upload.wikimedia.org/wikipedia/commons/a/ae/Pozna%C5%84_Pyrkon_2015_7_Cud%C3%B3w_%C5%9Awiata_7_Wonders.JPG' },
  '7-wonders-duel': { file: 'covers/7-wonders-duel.webp', source: 'wikipedia', sourceUrl: 'https://upload.wikimedia.org/wikipedia/en/6/6d/7_Wonders_Duel_cover.png' },
  'advanced-squad-leader': { file: 'covers/advanced-squad-leader.webp', source: 'wikipedia', sourceUrl: 'https://upload.wikimedia.org/wikipedia/en/a/a4/ASL_Rulebook_2nd_Edition.jpg' },
  'agricola': { file: 'covers/agricola.webp', source: 'wikipedia', sourceUrl: 'https://upload.wikimedia.org/wikipedia/commons/9/9e/Agricola_board_game.jpg' },
  'agricola-creatures': { file: 'covers/agricola-creatures.webp', source: 'wikidata', sourceUrl: 'http://commons.wikimedia.org/wiki/Special:FilePath/Agricola%20All%20Creatures%20Big%20and%20Small%20Play%20658%201703850095664.jpg' },
  'akropolis': { file: 'covers/akropolis.webp', source: 'wikidata', sourceUrl: 'http://commons.wikimedia.org/wiki/Special:FilePath/Akropolis%20-%20IMG%2020251011%20143939.jpg' },
  'alhambra': { file: 'covers/alhambra.webp', source: 'wikipedia', sourceUrl: 'https://upload.wikimedia.org/wikipedia/commons/d/d3/Deskohran%C3%AD_08-10-05_048.jpg' },
  'apples-to-apples': { file: 'covers/apples-to-apples.webp', source: 'wikipedia', sourceUrl: 'https://upload.wikimedia.org/wikipedia/en/0/03/Apples_to_Apples_cover.jpg' },
  'ark-nova': { file: 'covers/ark-nova.webp', source: 'wikipedia', sourceUrl: 'https://upload.wikimedia.org/wikipedia/en/4/42/Ark_Nova_box_cover.jpg' },
  'arkham-horror': { file: 'covers/arkham-horror.webp', source: 'wikipedia', sourceUrl: 'https://upload.wikimedia.org/wikipedia/en/e/ed/Arkham_Horror_revised_box.jpg' },
  'arkham-horror-lcg': { file: 'covers/arkham-horror-lcg.webp', source: 'wikipedia', sourceUrl: 'https://upload.wikimedia.org/wikipedia/en/d/d0/Arkham_Horror_Box.png' },
  'aventureros-al-tren': { file: 'covers/aventureros-al-tren.webp', source: 'manual', sourceUrl: 'https://upload.wikimedia.org/wikipedia/en/9/92/Ticket_to_Ride_Board_Game_Box_EN.jpg' },
  'axis-allies': { file: 'covers/axis-allies.webp', source: 'wikipedia', sourceUrl: 'https://upload.wikimedia.org/wikipedia/commons/6/6b/AaA_Logo.jpg' },
  'azul': { file: 'covers/azul.webp', source: 'wikipedia', sourceUrl: 'https://upload.wikimedia.org/wikipedia/en/2/23/Picture_of_Azul_game_box.jpg' },
  'backgammon': { file: 'covers/backgammon.webp', source: 'wikipedia', sourceUrl: 'https://upload.wikimedia.org/wikipedia/commons/2/21/Table_de_tric-trac_%28Paris_vers_1785%29_-_Mus%C3%A9e_des_arts_d%C3%A9coratifs_%28Paris%29_20210629_153520.jpg' },
  'balderdash': { file: 'covers/balderdash.webp', source: 'wikipedia', sourceUrl: 'https://upload.wikimedia.org/wikipedia/commons/d/d7/The_Balderdash_board_game_and_pieces_01.jpg' },
  'barrage': { file: 'covers/barrage.webp', source: 'wikidata', sourceUrl: 'http://commons.wikimedia.org/wiki/Special:FilePath/Playing%20board%20game%20-%20Play%20772%201710099142730.jpg' },
  'betrayal-house-hill': { file: 'covers/betrayal-house-hill.webp', source: 'wikidata', sourceUrl: 'http://commons.wikimedia.org/wiki/Special:FilePath/Play%20310%201688424591864.jpg' },
  'blood-bowl': { file: 'covers/blood-bowl.webp', source: 'wikipedia', sourceUrl: 'https://upload.wikimedia.org/wikipedia/commons/f/f7/Man_playing_Blood_Bowl.jpg' },
  'blood-on-the-clocktower': { file: 'covers/blood-on-the-clocktower.webp', source: 'wikipedia', sourceUrl: 'https://upload.wikimedia.org/wikipedia/commons/e/ea/Blood_on_the_Clocktower_game_in_progress.jpg' },
  'blood-rage': { file: 'covers/blood-rage.webp', source: 'wikipedia', sourceUrl: 'https://upload.wikimedia.org/wikipedia/en/5/5a/Blood_Rage_board_game_box_cover.jpg' },
  'bohnanza': { file: 'covers/bohnanza.webp', source: 'wikipedia', sourceUrl: 'https://upload.wikimedia.org/wikipedia/commons/6/65/Deskohran%C3%AD_08s4_235_-_Bohnanza.jpg' },
  'brass-birmingham': { file: 'covers/brass-birmingham.webp', source: 'wikidata', sourceUrl: 'http://commons.wikimedia.org/wiki/Special:FilePath/Playing%20board%20game%20-%20Play%201048%201724352635173.jpg' },
  'brass-lancashire': { file: 'covers/brass-lancashire.webp', source: 'wikipedia', sourceUrl: 'https://upload.wikimedia.org/wikipedia/commons/6/6c/Brasslogo.png' },
  'cabo': { file: 'covers/cabo.webp', source: 'wikipedia', sourceUrl: 'https://upload.wikimedia.org/wikipedia/en/a/a0/Cabo_box_art.jpg' },
  'calico': { file: 'covers/calico.webp', source: 'wikidata', sourceUrl: 'http://commons.wikimedia.org/wiki/Special:FilePath/Playing%20board%20game%20-%20Play%201060%201724585405829.jpg' },
  'camel-up': { file: 'covers/camel-up.webp', source: 'manual', sourceUrl: 'https://upload.wikimedia.org/wikipedia/en/f/fb/Camel_Up_box_cover.jpg' },
  'carcassonne': { file: 'covers/carcassonne.webp', source: 'wikipedia', sourceUrl: 'https://upload.wikimedia.org/wikipedia/en/5/5e/Carcassonne-game.jpg' },
  'cards-against-humanity': { file: 'covers/cards-against-humanity.webp', source: 'wikipedia', sourceUrl: 'https://upload.wikimedia.org/wikipedia/commons/8/85/Cards_Against_Humanity_logo_2009.svg' },
  'cartographers': { file: 'covers/cartographers.webp', source: 'wikidata', sourceUrl: 'http://commons.wikimedia.org/wiki/Special:FilePath/Cartographers%20A%20Roll%20Player%20Tale%20-%20IMG20260729225214.jpg' },
  'cascadia': { file: 'covers/cascadia.webp', source: 'wikipedia', sourceUrl: 'https://upload.wikimedia.org/wikipedia/en/7/79/Cascadia_box_cover.JPG' },
  'castles-of-burgundy': { file: 'covers/castles-of-burgundy.webp', source: 'wikipedia', sourceUrl: 'https://upload.wikimedia.org/wikipedia/commons/b/bf/Castles_of_Burgundy_%28Board_Game%29.jpg' },
  'catan': { file: 'covers/catan.webp', source: 'wikipedia', sourceUrl: 'https://upload.wikimedia.org/wikipedia/en/a/a3/Catan-2015-boxart.jpg' },
  'century-spice-road': { file: 'covers/century-spice-road.webp', source: 'wikipedia', sourceUrl: 'https://upload.wikimedia.org/wikipedia/en/e/e9/Century_Spice_Road_box_art.png' },
  'chess': { file: 'covers/chess.webp', source: 'wikipedia', sourceUrl: 'https://upload.wikimedia.org/wikipedia/commons/0/0a/FG_A-10_2.png' },
  'cluedo': { file: 'covers/cluedo.webp', source: 'wikipedia', sourceUrl: 'https://upload.wikimedia.org/wikipedia/commons/4/4c/Cluedo_Clue_pack_logo.png' },
  'codenames': { file: 'covers/codenames.webp', source: 'wikipedia', sourceUrl: 'https://upload.wikimedia.org/wikipedia/commons/5/5b/Codenames_with_key_card.jpg' },
  'commands-colors-ancients': { file: 'covers/commands-colors-ancients.webp', source: 'wikipedia', sourceUrl: 'https://upload.wikimedia.org/wikipedia/en/0/0b/Commands_and_Colors_Ancients.jpg' },
  'concept': { file: 'covers/concept.webp', source: 'wikipedia', sourceUrl: 'https://upload.wikimedia.org/wikipedia/en/1/11/Concept_boardgame_box.png' },
  'concordia': { file: 'covers/concordia.webp', source: 'wikipedia', sourceUrl: 'https://upload.wikimedia.org/wikipedia/commons/9/98/Playing_board_game_-_Play_1824_1763202284392.jpg' },
  'cyclades': { file: 'covers/cyclades.webp', source: 'wikidata', sourceUrl: 'http://commons.wikimedia.org/wiki/Special:FilePath/Playing%20board%20game%20-%20Play%201003%201723133395714.jpg' },
  'descent-journeys': { file: 'covers/descent-journeys.webp', source: 'wikipedia', sourceUrl: 'https://upload.wikimedia.org/wikipedia/commons/3/31/2012-01-21_Viernes_Ludop%C3%A1tico_04_%286857342177%29.jpg' },
  'disney-lorcana': { file: 'covers/disney-lorcana.webp', source: 'wikipedia', sourceUrl: 'https://upload.wikimedia.org/wikipedia/en/2/25/Lorcana_Card_Back.png' },
  'dixit': { file: 'covers/dixit.webp', source: 'wikipedia', sourceUrl: 'https://upload.wikimedia.org/wikipedia/commons/1/1b/Dixit_spiel_p_014.jpg' },
  'dixit-odyssey': { file: 'covers/dixit-odyssey.webp', source: 'wikipedia', sourceUrl: 'https://upload.wikimedia.org/wikipedia/en/7/7b/Dixitgame.jpg' },
  'dobble': { file: 'covers/dobble.webp', source: 'wikipedia', sourceUrl: 'https://upload.wikimedia.org/wikipedia/commons/8/84/Dobble_jeu.jpg' },
  'dominion': { file: 'covers/dominion.webp', source: 'wikipedia', sourceUrl: 'https://upload.wikimedia.org/wikipedia/en/b/b5/Dominion_game.jpg' },
  'dorfromantik': { file: 'covers/dorfromantik.webp', source: 'wikipedia', sourceUrl: 'https://upload.wikimedia.org/wikipedia/en/d/d7/Dorfromantik_board_game.webp' },
  'el-grande': { file: 'covers/el-grande.webp', source: 'wikipedia', sourceUrl: 'https://upload.wikimedia.org/wikipedia/en/b/b5/El_Grande.jpg' },
  'elder-sign': { file: 'covers/elder-sign.webp', source: 'wikipedia', sourceUrl: 'https://upload.wikimedia.org/wikipedia/en/2/25/Elder_Sign_Cards.jpg' },
  'eldritch-horror': { file: 'covers/eldritch-horror.webp', source: 'wikipedia', sourceUrl: 'https://upload.wikimedia.org/wikipedia/commons/b/b7/Eldrich_Horror_board_game_2017.jpg' },
  'exploding-kittens': { file: 'covers/exploding-kittens.webp', source: 'wikipedia', sourceUrl: 'https://upload.wikimedia.org/wikipedia/en/a/a6/Exploding_Kittens.png' },
  'flamecraft': { file: 'covers/flamecraft.webp', source: 'wikipedia', sourceUrl: 'https://upload.wikimedia.org/wikipedia/commons/d/d6/Juego_de_mesa_-_Play_271_1686162330413.jpg' },
  'food-chain-magnate': { file: 'covers/food-chain-magnate.webp', source: 'wikipedia', sourceUrl: 'https://upload.wikimedia.org/wikipedia/en/1/1e/Food_Chain_Magnate_box_art.jpg' },
  'forbidden-desert': { file: 'covers/forbidden-desert.webp', source: 'wikipedia', sourceUrl: 'https://upload.wikimedia.org/wikipedia/commons/8/8c/Forbidden_Desert_board_game_layout.jpg' },
  'forbidden-island': { file: 'covers/forbidden-island.webp', source: 'wikipedia', sourceUrl: 'https://upload.wikimedia.org/wikipedia/en/b/b0/Forbidden_Island_game_cover.jpg' },
  'frosthaven': { file: 'covers/frosthaven.webp', source: 'wikipedia', sourceUrl: 'https://upload.wikimedia.org/wikipedia/en/e/ee/Gloomhaven_Cover_Art.jpg' },
  'gloomhaven': { file: 'covers/gloomhaven.webp', source: 'wikipedia', sourceUrl: 'https://upload.wikimedia.org/wikipedia/en/e/ee/Gloomhaven_Cover_Art.jpg' },
  'grand-austria-hotel': { file: 'covers/grand-austria-hotel.webp', source: 'wikidata', sourceUrl: 'http://commons.wikimedia.org/wiki/Special:FilePath/Playing%20board%20game%20-%20Play%20965%201720890815192.jpg' },
  'great-western-trail': { file: 'covers/great-western-trail.webp', source: 'wikipedia', sourceUrl: 'https://upload.wikimedia.org/wikipedia/commons/0/07/Herders_on_the_trail_in_the_board_game_Great_Western_Trail.jpg' },
  'hanabi': { file: 'covers/hanabi.webp', source: 'wikipedia', sourceUrl: 'https://upload.wikimedia.org/wikipedia/en/b/b1/Hanabi_cover.jpg' },
  'hansa-teutonica': { file: 'covers/hansa-teutonica.webp', source: 'wikipedia', sourceUrl: 'https://upload.wikimedia.org/wikipedia/commons/9/9b/Cmglee_Hansa_Teutonica.jpg' },
  'harmonies': { file: 'covers/harmonies.webp', source: 'wikipedia', sourceUrl: 'https://upload.wikimedia.org/wikipedia/commons/f/f6/HarmoniesBoardgam.png' },
  'heat-pedal-to-the-metal': { file: 'covers/heat-pedal-to-the-metal.webp', source: 'wikipedia', sourceUrl: 'https://upload.wikimedia.org/wikipedia/en/8/8c/Heat-_Pedal_to_the_Metal_box.png' },
  'hero-realms': { file: 'covers/hero-realms.webp', source: 'wikipedia', sourceUrl: 'https://upload.wikimedia.org/wikipedia/en/5/53/Hero_Realms_Card_Game.jpg' },
  'heroquest': { file: 'covers/heroquest.webp', source: 'wikipedia', sourceUrl: 'https://upload.wikimedia.org/wikipedia/commons/2/21/HeroQuest.jpg' },
  'hive': { file: 'covers/hive.webp', source: 'wikipedia', sourceUrl: 'https://upload.wikimedia.org/wikipedia/commons/7/7d/Hive_%28Carbon_Edition%29_Game.jpg' },
  'isle-of-cats': { file: 'covers/isle-of-cats.webp', source: 'wikidata', sourceUrl: 'http://commons.wikimedia.org/wiki/Special:FilePath/The%20Isle%20of%20Cats%20-%204c534def-47e8-4e61-bcd1-3ff9fbd0e326~1-cropped.jpg' },
  'istanbul': { file: 'covers/istanbul.webp', source: 'wikipedia', sourceUrl: 'https://upload.wikimedia.org/wikipedia/en/7/7e/Istanbul_board_game_cover.jpg' },
  'jaipur': { file: 'covers/jaipur.webp', source: 'wikipedia', sourceUrl: 'https://upload.wikimedia.org/wikipedia/en/6/69/Japiur_card_game_box_cover.jpg' },
  'john-company': { file: 'covers/john-company.webp', source: 'wikipedia', sourceUrl: 'https://upload.wikimedia.org/wikipedia/en/b/b3/John_Company_Second_Edition_board_game_cover.png' },
  'jungle-speed': { file: 'covers/jungle-speed.webp', source: 'wikipedia', sourceUrl: 'https://upload.wikimedia.org/wikipedia/en/2/2e/Jungle_Speed_%28WiiWare%29.jpg' },
  'just-one': { file: 'covers/just-one.webp', source: 'wikipedia', sourceUrl: 'https://upload.wikimedia.org/wikipedia/en/6/61/Just_One_box.png' },
  'king-of-tokyo': { file: 'covers/king-of-tokyo.webp', source: 'wikipedia', sourceUrl: 'https://upload.wikimedia.org/wikipedia/commons/2/2c/Deskohran%C3%AD_2012_-_6869.JPG' },
  'kingdom-death-monster': { file: 'covers/kingdom-death-monster.webp', source: 'wikipedia', sourceUrl: 'https://upload.wikimedia.org/wikipedia/en/7/7a/Kingdom_death_monster_logo.jpg' },
  'kingdomino': { file: 'covers/kingdomino.webp', source: 'wikipedia', sourceUrl: 'https://upload.wikimedia.org/wikipedia/commons/6/6b/Kingdominologo.png' },
  'kutna-hora': { file: 'covers/kutna-hora.webp', source: 'wikidata', sourceUrl: 'http://commons.wikimedia.org/wiki/Special:FilePath/Kutn%C3%A1%20Hora%20The%20City%20of%20Silver%20Play%201005%201723314372153.jpg' },
  'le-havre': { file: 'covers/le-havre.webp', source: 'wikipedia', sourceUrl: 'https://upload.wikimedia.org/wikipedia/en/3/3e/Le_Havre_game.jpg' },
  'living-forest': { file: 'covers/living-forest.webp', source: 'wikipedia', sourceUrl: 'https://upload.wikimedia.org/wikipedia/commons/a/ac/Aske_Christiansen.jpg' },
  'lords-of-waterdeep': { file: 'covers/lords-of-waterdeep.webp', source: 'wikipedia', sourceUrl: 'https://upload.wikimedia.org/wikipedia/en/e/ef/DnD_LOW.png' },
  'lost-cities': { file: 'covers/lost-cities.webp', source: 'wikipedia', sourceUrl: 'https://upload.wikimedia.org/wikipedia/commons/b/b5/Exploradores_board.jpg' },
  'lost-ruins-arnak': { file: 'covers/lost-ruins-arnak.webp', source: 'wikipedia', sourceUrl: 'https://upload.wikimedia.org/wikipedia/en/0/0c/Lost_Ruins_of_Arnak_box_cover.jpg' },
  'lotr-lcg': { file: 'covers/lotr-lcg.webp', source: 'wikipedia', sourceUrl: 'https://upload.wikimedia.org/wikipedia/en/5/5f/The-Lord-of-the-Rings-The-Card-Game-box-layout.png' },
  'love-letter': { file: 'covers/love-letter.webp', source: 'wikipedia', sourceUrl: 'https://upload.wikimedia.org/wikipedia/commons/b/b4/Love_Letter_%28juego%29.jpg' },
  'machi-koro': { file: 'covers/machi-koro.webp', source: 'wikipedia', sourceUrl: 'https://upload.wikimedia.org/wikipedia/en/5/58/Machi_Koro_US_Cover_IDW_Panadsaurus.jpg' },
  'mage-knight': { file: 'covers/mage-knight.webp', source: 'wikipedia', sourceUrl: 'https://upload.wikimedia.org/wikipedia/en/1/12/MageKnightLogo.png' },
  'magic-the-gathering': { file: 'covers/magic-the-gathering.webp', source: 'wikipedia', sourceUrl: 'https://upload.wikimedia.org/wikipedia/commons/3/3f/Magicthegathering-logo.svg' },
  'memoir-44': { file: 'covers/memoir-44.webp', source: 'wikipedia', sourceUrl: 'https://upload.wikimedia.org/wikipedia/commons/6/67/Deskohran%C3%AD_08-09-29_007.jpg' },
  'modern-art': { file: 'covers/modern-art.webp', source: 'wikidata', sourceUrl: 'http://commons.wikimedia.org/wiki/Special:FilePath/Play%20886%201716049633957.jpg' },
  'monopoly': { file: 'covers/monopoly.webp', source: 'wikipedia', sourceUrl: 'https://upload.wikimedia.org/wikipedia/commons/d/df/German_Monopoly_board_in_the_middle_of_a_game.jpg' },
  'mysterium': { file: 'covers/mysterium.webp', source: 'wikipedia', sourceUrl: 'https://upload.wikimedia.org/wikipedia/en/5/5e/Mysterium_board_game_cover.jpg' },
  'nemesis': { file: 'covers/nemesis.webp', source: 'wikidata', sourceUrl: 'http://commons.wikimedia.org/wiki/Special:FilePath/Playing%20board%20game%20-%20Play%20213%201681550178485.jpg' },
  'netrunner': { file: 'covers/netrunner.webp', source: 'wikipedia', sourceUrl: 'https://upload.wikimedia.org/wikipedia/en/f/fc/Android_Netrunner_Core_Set_Box.png' },
  'next-station-london': { file: 'covers/next-station-london.webp', source: 'wikidata', sourceUrl: 'http://commons.wikimedia.org/wiki/Special:FilePath/Next%20Station%20London%20-%20IMG20260730140820.jpg' },
  'no-thanks': { file: 'covers/no-thanks.webp', source: 'wikipedia', sourceUrl: 'https://upload.wikimedia.org/wikipedia/commons/b/b8/No_Thanks%21.jpg' },
  'onitama': { file: 'covers/onitama.webp', source: 'wikipedia', sourceUrl: 'https://upload.wikimedia.org/wikipedia/commons/5/50/Onitama_Logo.svg' },
  'pandemic': { file: 'covers/pandemic.webp', source: 'wikipedia', sourceUrl: 'https://upload.wikimedia.org/wikipedia/en/3/36/Pandemic_game.jpg' },
  'pandemic-legacy-1': { file: 'covers/pandemic-legacy-1.webp', source: 'wikidata', sourceUrl: 'http://commons.wikimedia.org/wiki/Special:FilePath/Playing%20board%20game%20-%20IMG%2020240110%20183908.jpg' },
  'pandemic-legacy-2': { file: 'covers/pandemic-legacy-2.webp', source: 'wikidata', sourceUrl: 'http://commons.wikimedia.org/wiki/Special:FilePath/Playing%20board%20game%20-%20Play%201337%201736534208315.jpg' },
  'parchis': { file: 'covers/parchis.webp', source: 'wikipedia', sourceUrl: 'https://upload.wikimedia.org/wikipedia/commons/c/cd/Parch%C3%ADs.svg' },
  'patchwork': { file: 'covers/patchwork.webp', source: 'wikidata', sourceUrl: 'http://commons.wikimedia.org/wiki/Special:FilePath/Play%20303%201687690103040.jpg' },
  'patchwork-doodle': { file: 'covers/patchwork-doodle.webp', source: 'wikidata', sourceUrl: 'http://commons.wikimedia.org/wiki/Special:FilePath/Play%2032%201667332104113.jpg' },
  'paths-of-glory': { file: 'covers/paths-of-glory.webp', source: 'wikipedia', sourceUrl: 'https://upload.wikimedia.org/wikipedia/en/f/fa/Paths_of_glory.jpg' },
  'pax-pamir': { file: 'covers/pax-pamir.webp', source: 'wikipedia', sourceUrl: 'https://upload.wikimedia.org/wikipedia/en/2/29/Pax_Pamir_second_ediiton_box_cover.jpg' },
  'phase-10': { file: 'covers/phase-10.webp', source: 'wikipedia', sourceUrl: 'https://upload.wikimedia.org/wikipedia/commons/e/e3/Phase_10.jpg' },
  'photosynthesis': { file: 'covers/photosynthesis.webp', source: 'wikipedia', sourceUrl: 'https://upload.wikimedia.org/wikipedia/commons/9/97/A_game_of_Photosynthesis_in_progress.jpg' },
  'pictionary': { file: 'covers/pictionary.webp', source: 'wikipedia', sourceUrl: 'https://upload.wikimedia.org/wikipedia/commons/5/5d/Pictionary_Party.jpg' },
  'power-grid': { file: 'covers/power-grid.webp', source: 'wikipedia', sourceUrl: 'https://upload.wikimedia.org/wikipedia/commons/6/60/Hry_a_hlavolamy_2008_-_Vysok%C3%A9_nap%C4%9Bt%C3%AD_1.jpg' },
  'puerto-rico': { file: 'covers/puerto-rico.webp', source: 'wikipedia', sourceUrl: 'https://upload.wikimedia.org/wikipedia/commons/1/1d/Deskohran%C3%AD_08-10-04_130.jpg' },
  'quacks-quedlinburg': { file: 'covers/quacks-quedlinburg.webp', source: 'wikipedia', sourceUrl: 'https://upload.wikimedia.org/wikipedia/en/e/e3/The_Quacks_of_Quedlinburg_box_cover.jpg' },
  'quarto': { file: 'covers/quarto.webp', source: 'wikipedia', sourceUrl: 'https://upload.wikimedia.org/wikipedia/commons/b/b4/QuartoSpiel.JPG' },
  'queendomino': { file: 'covers/queendomino.webp', source: 'wikipedia', sourceUrl: 'https://upload.wikimedia.org/wikipedia/en/a/a3/Kingdomino_Box_Cover.png' },
  'quoridor': { file: 'covers/quoridor.webp', source: 'wikipedia', sourceUrl: 'https://upload.wikimedia.org/wikipedia/commons/8/84/Quoridor_1.jpg' },
  'race-for-the-galaxy': { file: 'covers/race-for-the-galaxy.webp', source: 'wikipedia', sourceUrl: 'https://upload.wikimedia.org/wikipedia/commons/6/62/Race_for_the_Galaxy_table_gameplay.jpg' },
  'radlands': { file: 'covers/radlands.webp', source: 'wikipedia', sourceUrl: 'https://upload.wikimedia.org/wikipedia/en/2/2c/Radlands_cover_art.jpg' },
  'resistance-avalon': { file: 'covers/resistance-avalon.webp', source: 'wikidata', sourceUrl: 'http://commons.wikimedia.org/wiki/Special:FilePath/Playing%20board%20game%20-%20Play%201521%201745100006682.jpg' },
  'revive': { file: 'covers/revive.webp', source: 'wikidata', sourceUrl: 'http://commons.wikimedia.org/wiki/Special:FilePath/Juego%20de%20mesa%20-%20Play%20455%201693332388678.jpg' },
  'risk': { file: 'covers/risk.webp', source: 'wikipedia', sourceUrl: 'https://upload.wikimedia.org/wikipedia/commons/8/88/Riskgame_logo.png' },
  'robinson-crusoe': { file: 'covers/robinson-crusoe.webp', source: 'wikipedia', sourceUrl: 'https://upload.wikimedia.org/wikipedia/commons/2/26/Pyrkon_2017_Robinson_Crusoe_Board_Game_4280061.jpg' },
  'root': { file: 'covers/root.webp', source: 'wikipedia', sourceUrl: 'https://upload.wikimedia.org/wikipedia/commons/9/9f/Turn_1_in_board_game_Root.jpg' },
  'rummikub': { file: 'covers/rummikub.webp', source: 'wikipedia', sourceUrl: 'https://upload.wikimedia.org/wikipedia/commons/d/d7/Rummikub1.jpg' },
  'sagrada': { file: 'covers/sagrada.webp', source: 'wikipedia', sourceUrl: 'https://upload.wikimedia.org/wikipedia/commons/4/4e/A_nearly_complete_window_in_Sagrada.jpg' },
  'santorini': { file: 'covers/santorini.webp', source: 'wikipedia', sourceUrl: 'https://upload.wikimedia.org/wikipedia/commons/e/ec/Santorini_game_render.jpg' },
  'scattergories': { file: 'covers/scattergories.webp', source: 'wikipedia', sourceUrl: 'https://upload.wikimedia.org/wikipedia/en/a/a7/ScattergoriesBox.jpg' },
  'scout': { file: 'covers/scout.webp', source: 'wikidata', sourceUrl: 'http://commons.wikimedia.org/wiki/Special:FilePath/Scout%20Kei%20Kajino.jpg' },
  'scrabble': { file: 'covers/scrabble.webp', source: 'wikipedia', sourceUrl: 'https://upload.wikimedia.org/wikipedia/commons/c/c6/Tablero_de_ScrabbleIMG_20201008_175354.jpg' },
  'scythe': { file: 'covers/scythe.webp', source: 'wikipedia', sourceUrl: 'https://upload.wikimedia.org/wikipedia/en/1/1a/Scythe_boxart.png' },
  'secret-hitler': { file: 'covers/secret-hitler.webp', source: 'wikipedia', sourceUrl: 'https://upload.wikimedia.org/wikipedia/commons/8/89/Secret_Hitler.svg' },
  'sherlock-holmes-consulting': { file: 'covers/sherlock-holmes-consulting.webp', source: 'wikipedia', sourceUrl: 'https://upload.wikimedia.org/wikipedia/en/9/9a/Cover_of_Sherlock_Holmes_Consulting_Detective_book_game.png' },
  'skip-bo': { file: 'covers/skip-bo.webp', source: 'wikipedia', sourceUrl: 'https://upload.wikimedia.org/wikipedia/en/8/8d/Skip-Bo_cover.JPG' },
  'sleeping-gods': { file: 'covers/sleeping-gods.webp', source: 'wikidata', sourceUrl: 'http://commons.wikimedia.org/wiki/Special:FilePath/Juego%20de%20mesa%20-%20Play%20107%201674233774623.jpg' },
  'space-hulk': { file: 'covers/space-hulk.webp', source: 'wikipedia', sourceUrl: 'https://upload.wikimedia.org/wikipedia/en/6/6a/Space_hulk_box.jpg' },
  'splendor': { file: 'covers/splendor.webp', source: 'wikipedia', sourceUrl: 'https://upload.wikimedia.org/wikipedia/en/2/2e/BoardGameSplendorLogoFairUse.jpg' },
  'splendor-duel': { file: 'covers/splendor-duel.webp', source: 'wikidata', sourceUrl: 'http://commons.wikimedia.org/wiki/Special:FilePath/Play%20533%201697289143094.jpg' },
  'star-realms': { file: 'covers/star-realms.webp', source: 'wikipedia', sourceUrl: 'https://upload.wikimedia.org/wikipedia/commons/d/dd/%D0%9A%D0%BB%D1%83%D0%B1_%D0%BD%D0%B0%D1%81%D1%82%D1%96%D0%BB%D1%8C%D0%BD%D0%B8%D1%85_%D1%96%D0%B3%D0%BE%D1%80_03.jpg' },
  'star-wars-deckbuilding': { file: 'covers/star-wars-deckbuilding.webp', source: 'wikipedia', sourceUrl: 'https://upload.wikimedia.org/wikipedia/en/e/e2/Star_Wars_The_Deckbuilding_Game.webp' },
  'star-wars-rebellion': { file: 'covers/star-wars-rebellion.webp', source: 'wikipedia', sourceUrl: 'https://upload.wikimedia.org/wikipedia/en/d/d4/Star_Wars_Rebellion_%28Board_Game%29_Box_Art.png' },
  'stone-age': { file: 'covers/stone-age.webp', source: 'wikipedia', sourceUrl: 'https://upload.wikimedia.org/wikipedia/commons/9/96/Deskohran%C3%AD_08-09-27_225.jpg' },
  'sushi-go': { file: 'covers/sushi-go.webp', source: 'wikipedia', sourceUrl: 'https://upload.wikimedia.org/wikipedia/en/9/98/Sushi_Go%21_box.jpg' },
  'sushi-go-party': { file: 'covers/sushi-go-party.webp', source: 'wikidata', sourceUrl: 'http://commons.wikimedia.org/wiki/Special:FilePath/Sushi%20Go%20Party%21%20-%201a986acc-cfa3-4e20-8da8-d7d4a5da2d56~1.jpg' },
  'taboo': { file: 'covers/taboo.webp', source: 'wikipedia', sourceUrl: 'https://upload.wikimedia.org/wikipedia/commons/1/19/Taboo_02.jpg' },
  'tak': { file: 'covers/tak.webp', source: 'wikipedia', sourceUrl: 'https://upload.wikimedia.org/wikipedia/commons/5/5a/Game_of_Tak.jpg' },
  'takenoko': { file: 'covers/takenoko.webp', source: 'wikipedia', sourceUrl: 'https://upload.wikimedia.org/wikipedia/commons/b/b6/Deskohran%C3%AD_2012_-_6818.JPG' },
  'tapestry': { file: 'covers/tapestry.webp', source: 'wikipedia', sourceUrl: 'https://upload.wikimedia.org/wikipedia/en/b/bd/Tapestry_board_game_box_art.png' },
  'telestrations': { file: 'covers/telestrations.webp', source: 'wikipedia', sourceUrl: 'https://upload.wikimedia.org/wikipedia/commons/5/50/Telestrations_party_game_of_drawing_and_guessing_02.jpg' },
  'terra-mystica': { file: 'covers/terra-mystica.webp', source: 'wikipedia', sourceUrl: 'https://upload.wikimedia.org/wikipedia/commons/6/6a/Terra_Mystica_-_detail.jpg' },
  'terraforming-mars': { file: 'covers/terraforming-mars.webp', source: 'manual', sourceUrl: 'https://upload.wikimedia.org/wikipedia/en/f/f0/Terraforming_Mars_board_game_box_cover.jpg' },
  'the-chameleon': { file: 'covers/the-chameleon.webp', source: 'wikipedia', sourceUrl: 'https://upload.wikimedia.org/wikipedia/commons/8/8b/The_Chameleon_party_game_box%2C_rules%2C_and_cards_02.jpg' },
  'the-crew-planet-nine': { file: 'covers/the-crew-planet-nine.webp', source: 'wikidata', sourceUrl: 'http://commons.wikimedia.org/wiki/Special:FilePath/Playing%20board%20game%20-%20IMG%2020240107%20133506.jpg' },
  'the-game': { file: 'covers/the-game.webp', source: 'wikidata', sourceUrl: 'http://commons.wikimedia.org/wiki/Special:FilePath/The%20Game%20About%20Wikipedia%202.jpg' },
  'the-mind': { file: 'covers/the-mind.webp', source: 'wikipedia', sourceUrl: 'https://upload.wikimedia.org/wikipedia/commons/c/ca/Themind.png' },
  'the-white-castle': { file: 'covers/the-white-castle.webp', source: 'wikidata', sourceUrl: 'http://commons.wikimedia.org/wiki/Special:FilePath/The%20White%20Castle%20Play%201398%201739098075892.jpg' },
  'this-war-of-mine': { file: 'covers/this-war-of-mine.webp', source: 'wikipedia', sourceUrl: 'https://upload.wikimedia.org/wikipedia/en/3/36/This_War_of_Mine_board_game_box_cover.webp' },
  'too-many-bones': { file: 'covers/too-many-bones.webp', source: 'wikidata', sourceUrl: 'http://commons.wikimedia.org/wiki/Special:FilePath/Too%20Many%20Bones%20-%20IMG%2020240127%20182430.jpg' },
  'trivial-pursuit': { file: 'covers/trivial-pursuit.webp', source: 'wikipedia', sourceUrl: 'https://upload.wikimedia.org/wikipedia/commons/1/1a/Trivial_Pursuit_icon.png' },
  'twilight-imperium': { file: 'covers/twilight-imperium.webp', source: 'wikipedia', sourceUrl: 'https://upload.wikimedia.org/wikipedia/en/7/77/Twilight-imperium-layout_12.jpg' },
  'twilight-struggle': { file: 'covers/twilight-struggle.webp', source: 'wikipedia', sourceUrl: 'https://upload.wikimedia.org/wikipedia/en/c/c1/GMTtwilightStruggle.jpg' },
  'tzolkin': { file: 'covers/tzolkin.webp', source: 'wikidata', sourceUrl: 'http://commons.wikimedia.org/wiki/Special:FilePath/Tzolk%27in%20board%20game.jpg' },
  'underwater-cities': { file: 'covers/underwater-cities.webp', source: 'wikidata', sourceUrl: 'http://commons.wikimedia.org/wiki/Special:FilePath/Playing%20board%20game%20-%20Play%20599%201701456997951.jpg' },
  'uno': { file: 'covers/uno.webp', source: 'wikipedia', sourceUrl: 'https://upload.wikimedia.org/wikipedia/commons/f/f9/UNO_Logo.svg' },
  'viticulture': { file: 'covers/viticulture.webp', source: 'wikidata', sourceUrl: 'http://commons.wikimedia.org/wiki/Special:FilePath/Playing%20board%20game%20-%20Play%20578%201699743964830.jpg' },
  'voyages-marco-polo': { file: 'covers/voyages-marco-polo.webp', source: 'wikidata', sourceUrl: 'http://commons.wikimedia.org/wiki/Special:FilePath/Play%201868%201766745157620.jpg' },
  'wavelength': { file: 'covers/wavelength.webp', source: 'wikipedia', sourceUrl: 'https://upload.wikimedia.org/wikipedia/commons/b/b0/The_Wavelength_party_game_box_and_elements_01.jpg' },
  'werewords': { file: 'covers/werewords.webp', source: 'wikipedia', sourceUrl: 'https://upload.wikimedia.org/wikipedia/en/2/29/Werewords_smallsize.jpg' },
  'wingspan': { file: 'covers/wingspan.webp', source: 'wikipedia', sourceUrl: 'https://upload.wikimedia.org/wikipedia/en/c/c3/3d-wingspan-768x752.png' },
  'zombicide': { file: 'covers/zombicide.webp', source: 'wikipedia', sourceUrl: 'https://upload.wikimedia.org/wikipedia/commons/0/07/Concentration_%287979594729%29.jpg' },
}
