/**
 * El catálogo amplio, una línea por juego. Es la SEMILLA de la base de datos, no
 * un dato de ejecución: lo leen `npm run seed:games` y `npm run ingest:bgg`, y de
 * ahí baja a Postgres, que es de donde lo busca la app.
 *
 * Vive en `scripts/` justo por eso. Estuvo dentro de `src/games/` mientras el
 * catálogo entero viajaba en el bundle; con el catálogo creciendo a decenas de
 * miles de juegos, meterlo en el JavaScript que descarga cada visita dejó de tener
 * sentido. Lo que sigue viajando en la app son los 24 de `definitions/`, que es lo
 * que la hace funcionar sin red.
 *
 * Columnas:
 *   slug · nombre · icono · lema · jugadores (min, max) · minutos (min, max) · dificultad · hoja
 *
 * La «hoja» es lo que se apunta al acabar la partida:
 *   points  se cuentan puntos y gana el que más tiene
 *   lowest  se cuentan puntos y gana el que menos tiene
 *   coop    todos contra el tablero: ganáis o perdéis juntos
 *   teams   por bandos: gana más de uno, pero no todos
 *   win     sin puntos, solo hay un ganador
 *
 * Jugadores y duración son los de la caja del juego base (sin expansiones). La
 * dificultad es cuánto cuesta ponerse a jugar, no cuánto cuesta ganar.
 *
 * Los juegos con hoja de puntuación DETALLADA (con los conceptos propios del juego) van
 * en `src/games/definitions/`, no aquí. Una chuleta de reglas por sí sola no basta para
 * promocionar un juego: los más jugados del catálogo la llevan sin salir de aquí,
 * escrita aparte en `catalog.rules.ts`. Si un juego está en los dos sitios, manda
 * `definitions/`.
 *
 * La regla de qué hoja y qué color le tocan a cada fila no está aquí, sino en
 * `expandCatalogSeedRow` (`src/games/catalog.ts`): es la misma que reconstruye un
 * juego que llega del servidor, y no puede haber dos.
 */
import type { CatalogRow } from '../src/games/catalog'

export const CATALOG_ROWS: CatalogRow[] = [
  // ---------------------------------------------------------------------------
  // Los grandes eurogames
  // ---------------------------------------------------------------------------
  ['agricola', 'Agricola', '🚜', 'Una granja del siglo XVII y una familia a la que dar de comer', 1, 4, 60, 120, 'hard', 'points'],
  ['agricola-creatures', 'Agricola: All Creatures Big and Small', '🐖', 'Agricola a dos, solo con los animales y sin pasar hambre', 2, 2, 30, 30, 'medium', 'points'],
  ['caverna', 'Caverna: The Cave Farmers', '⛏️', 'Enanos que excavan la montaña, siembran y salen de expedición', 1, 7, 30, 210, 'hard', 'points'],
  ['le-havre', 'Le Havre', '⚓', 'Barcos, edificios y un puerto que no para de crecer', 1, 5, 60, 200, 'hard', 'points'],
  ['ora-et-labora', 'Ora et Labora', '⛪', 'Un monasterio medieval, sus tierras y su rueda de producción', 1, 4, 60, 180, 'hard', 'points'],
  ['puerto-rico', 'Puerto Rico', '🌴', 'Elige rol, todos lo usan: el clásico que fundó los eurogames', 2, 5, 90, 150, 'hard', 'points'],
  ['puerto-rico-1897', 'Puerto Rico 1897', '🚢', 'El Puerto Rico de siempre, reeditado y reequilibrado', 2, 5, 90, 150, 'hard', 'points'],
  ['power-grid', 'Power Grid', '⚡', 'Subastas de centrales y una red eléctrica que alimentar', 2, 6, 120, 120, 'hard', 'points'],
  ['teotihuacan', 'Teotihuacan: City of Gods', '🌞', 'Dados-trabajadores que envejecen mientras levantas la pirámide', 1, 4, 60, 120, 'hard', 'points'],
  ['anachrony', 'Anachrony', '⌛', 'Pide recursos al futuro y devuélvelos antes de la paradoja', 1, 4, 30, 120, 'hard', 'points'],
  ['maracaibo', 'Maracaibo', '🏴‍☠️', 'Vuelta al Caribe con tres potencias coloniales y una campaña', 1, 4, 40, 160, 'hard', 'points'],
  ['clans-of-caledonia', 'Clans of Caledonia', '🥃', 'Clanes escoceses que producen, exportan y destilan whisky', 1, 4, 30, 120, 'hard', 'points'],
  ['hansa-teutonica', 'Hansa Teutonica', '🧭', 'Rutas comerciales hanseáticas y mejoras que se pisan entre sí', 2, 5, 45, 90, 'medium', 'points'],
  ['troyes', 'Troyes', '🎲', 'Compra los dados de tus vecinos para pagar tus acciones', 2, 4, 90, 90, 'hard', 'points'],
  ['tigris-euphrates', 'Tigris & Euphrates', '🏺', 'Cuatro civilizaciones a la vez: tu puntuación es la del color más flojo', 2, 4, 60, 90, 'hard', 'points'],
  ['el-grande', 'El Grande', '👑', 'Caballeros a las regiones de Castilla y mayorías que se cuentan tres veces', 2, 5, 60, 120, 'hard', 'points'],
  ['stone-age', 'Stone Age', '🪨', 'Prehistoria amable: colocar trabajadores, tirar dados y comer', 2, 4, 60, 90, 'medium', 'points'],
  ['lords-of-waterdeep', 'Lords of Waterdeep', '🏙️', 'Los señores ocultos de la ciudad contratan aventureros', 2, 5, 60, 120, 'medium', 'points'],
  ['istanbul', 'Istanbul', '🛒', 'Recorre el bazar con tus ayudantes hasta juntar cinco rubíes', 2, 5, 40, 60, 'medium', 'points'],
  ['five-tribes', 'Five Tribes', '🕌', 'Mancala en Naqala: mueves meeples y aprovechas donde caen', 2, 4, 40, 80, 'hard', 'points'],
  ['alhambra', 'Alhambra', '🏯', 'Compra edificios con la moneda exacta y levanta tu palacio', 2, 6, 45, 60, 'easy', 'points'],
  ['viticulture-tuscany', 'Viticulture: Tuscany Essential Edition', '🏘️', 'La expansión imprescindible: más edificios, más estaciones', 1, 6, 60, 100, 'hard', 'points'],
  ['champions-of-midgard', 'Champions of Midgard', '🐲', 'Un puerto vikingo que contrata guerreros para matar monstruos', 2, 4, 60, 90, 'medium', 'points'],
  ['indonesia', 'Indonesia', '🛶', 'Fusiones empresariales y rutas de mercancías en el archipiélago', 2, 5, 180, 300, 'hard', 'points'],
  ['the-gallerist', 'The Gallerist', '🖼️', 'Descubre artistas, infla su precio y llena tu galería', 1, 4, 60, 150, 'hard', 'points'],
  ['lisboa', 'Lisboa', '🌊', 'Reconstruir Lisboa tras el terremoto de 1755', 1, 4, 60, 180, 'hard', 'points'],
  ['on-mars', 'On Mars', '🔴', 'Colonia marciana entre la órbita y la superficie', 1, 4, 90, 150, 'hard', 'points'],
  ['weather-machine', 'Weather Machine', '🌦️', 'Arregla el clima que estropeó tu propio invento', 1, 4, 60, 180, 'hard', 'points'],
  ['vinhos', 'Vinhos: Deluxe Edition', '🍷', 'Bodegas portuguesas, enólogos y ferias del vino', 1, 4, 60, 150, 'hard', 'points'],
  ['escape-plan', 'Escape Plan', '💰', 'Atraco resuelto: ahora hay que salir de la ciudad con el botín', 1, 5, 60, 120, 'hard', 'points'],
  ['carnegie', 'Carnegie', '🏢', 'Un imperio empresarial americano departamento a departamento', 1, 4, 60, 120, 'hard', 'points'],
  ['nucleum', 'Nucleum', '⚛️', 'Sajonia electrificada a base de carbón, uranio y raíles', 1, 4, 60, 150, 'hard', 'points'],
  ['voidfall', 'Voidfall', '🌑', 'Civilizaciones galácticas sin azar y con muchísimo cálculo', 1, 4, 100, 200, 'hard', 'points'],
  ['hadrians-wall', "Hadrian's Wall", '🧱', 'Rellena tu hoja levantando la muralla romana antes que nadie', 1, 6, 45, 60, 'hard', 'points'],
  ['obsession', 'Obsession', '🎩', 'Alta sociedad victoriana: reforma tu casa y organiza fiestas', 1, 4, 45, 90, 'hard', 'points'],
  ['the-white-castle', 'The White Castle', '🏯', 'Tres puentes, dados de colores y una hora larga de decisiones', 1, 4, 45, 80, 'medium', 'points'],
  ['kutna-hora', 'Kutná Hora: The City of Silver', '🥈', 'La plata de Bohemia y una ciudad cuyo mercado se mueve solo', 2, 4, 60, 120, 'hard', 'points'],
  ['distilled', 'Distilled', '🥃', 'Destila ron, whisky o ginebra y envejécelo en barrica', 1, 4, 60, 120, 'medium', 'points'],
  ['expeditions', 'Expeditions', '🤖', 'La secuela de Scythe: mechas, expediciones y cartas mejorables', 1, 5, 60, 90, 'hard', 'points'],
  ['revive', 'Revive', '🧊', 'Deshielo poscolapso: cinco tribus buscan la ciudad enterrada', 1, 4, 60, 120, 'hard', 'points'],
  ['bitoku', 'Bitoku', '🍄', 'Espíritus del bosque japonés y un río de peregrinos', 1, 4, 90, 120, 'hard', 'points'],
  ['darwins-journey', "Darwin's Journey", '🐢', 'Galápagos: forma a tus trabajadores antes de mandarlos a explorar', 1, 4, 60, 120, 'hard', 'points'],
  ['newton', 'Newton', '🔭', 'Ciencia del XVII: viaja, estudia y publica antes que tus colegas', 1, 4, 90, 120, 'hard', 'points'],
  ['trickerion', 'Trickerion: Legends of Illusion', '🎩', 'Magos de vodevil que ensayan trucos y llenan el teatro', 2, 4, 90, 180, 'hard', 'points'],
  ['grand-austria-hotel', 'Grand Austria Hotel', '☕', 'Un café vienés: sirve al cliente exacto y prepara su habitación', 2, 4, 60, 120, 'hard', 'points'],
  ['lorenzo-il-magnifico', 'Lorenzo il Magnifico', '⛲', 'Renacimiento florentino con dados comunes y mucha carta', 2, 4, 60, 120, 'hard', 'points'],
  ['coimbra', 'Coimbra', '🎓', 'Subasta tus dados por el favor de las familias portuguesas', 2, 4, 60, 75, 'medium', 'points'],
  ['the-red-cathedral', 'The Red Cathedral', '⛪', 'Gremios rusos construyendo la catedral de San Basilio', 1, 4, 60, 80, 'medium', 'points'],
  ['voyages-marco-polo', 'The Voyages of Marco Polo', '🐫', 'Ruta de la seda: tus dados salen como salen, apáñatelas', 2, 4, 40, 100, 'hard', 'points'],
  ['marco-polo-ii', 'Marco Polo II: In the Service of the Khan', '🗺️', 'La secuela: mismo motor de dados, mapa y contratos nuevos', 2, 4, 60, 120, 'hard', 'points'],
  ['nations', 'Nations', '🌐', 'Civilizaciones simultáneas: crece sin quedarte sin comida', 1, 5, 40, 200, 'hard', 'points'],
  ['tapestry', 'Tapestry', '🧶', 'Avanza por cuatro vías civilizatorias al ritmo que quieras', 1, 5, 90, 120, 'medium', 'points'],
  ['sidereal-confluence', 'Sidereal Confluence', '🤝', 'Nueve razas alienígenas negociando todas a la vez, a gritos', 4, 9, 120, 180, 'hard', 'points'],
  ['elysium', 'Elysium', '🏺', 'Mitología griega: combina cartas y llévalas al Elíseo a tiempo', 2, 4, 60, 75, 'medium', 'points'],
  ['beyond-the-sun', 'Beyond the Sun', '🛰️', 'Árbol tecnológico compartido: quien lo abre, lo abre para todos', 2, 4, 60, 120, 'hard', 'points'],
  ['beyond-the-sun-leaders', 'Beyond the Sun: Leaders of the New Dawn', '👩‍🚀', 'La expansión con líderes, facciones y nuevas tecnologías', 2, 4, 60, 120, 'hard', 'points'],
  ['ares-expedition', 'Terraforming Mars: Ares Expedition', '🚀', 'Terraformar Marte en una hora, con roles simultáneos', 1, 4, 45, 60, 'medium', 'points'],
  ['race-for-the-galaxy', 'Race for the Galaxy', '🌠', 'Roles simultáneos e iconografía densa: rápido cuando lo pillas', 2, 4, 30, 60, 'hard', 'points'],
  ['race-gathering-storm', 'Race for the Galaxy: The Gathering Storm', '⛈️', 'Primera expansión: objetivos, quinto jugador y modo en solitario', 1, 5, 30, 60, 'hard', 'points'],
  ['roll-for-the-galaxy', 'Roll for the Galaxy', '🎲', 'Race for the Galaxy con dados metidos en cubiletes', 2, 5, 45, 45, 'medium', 'points'],
  ['res-arcana', 'Res Arcana', '🔮', 'Magos con ocho cartas: monta tu motor de esencias en media hora', 2, 4, 20, 60, 'medium', 'points'],
  ['innovation', 'Innovation', '💡', 'Cartas que se solapan y reglas que cambian con cada era', 2, 4, 30, 60, 'hard', 'points'],
  ['paladins-west-kingdom', 'Paladins of the West Kingdom', '🏇', 'Un paladín por ronda te dice qué puedes hacer esta vez', 1, 4, 90, 120, 'hard', 'points'],
  ['architects-west-kingdom', 'Architects of the West Kingdom', '🧱', 'Trabajadores que se acumulan y se pueden delatar por dinero', 1, 5, 60, 80, 'medium', 'points'],
  ['viscounts-west-kingdom', 'Viscounts of the West Kingdom', '📚', 'Da vueltas al reino y decide si subes o bajas con él', 1, 4, 60, 90, 'medium', 'points'],
  ['raiders-north-sea', 'Raiders of the North Sea', '🪓', 'Coloca un trabajador, coge otro y vete de saqueo', 2, 4, 60, 80, 'medium', 'points'],
  ['explorers-north-sea', 'Explorers of the North Sea', '⛵', 'Islas del norte: mueve tu barco, coloniza y arrea ganado', 2, 4, 45, 60, 'easy', 'points'],
  ['shipwrights-north-sea', 'Shipwrights of the North Sea', '🔨', 'Un astillero vikingo y vecinos a los que sobornar', 2, 5, 60, 60, 'medium', 'points'],
  ['raiders-of-scythia', 'Raiders of Scythia', '🏹', 'Los saqueadores del norte, ahora a caballo por la estepa', 1, 4, 60, 80, 'medium', 'points'],
  ['wayfarers-south-tigris', 'Wayfarers of the South Tigris', '🌙', 'Cartógrafos abasíes midiendo cielo y tierra', 1, 4, 60, 90, 'hard', 'points'],
  ['scholars-south-tigris', 'Scholars of the South Tigris', '📜', 'La Casa de la Sabiduría de Bagdad, dado a dado', 1, 4, 60, 90, 'hard', 'points'],
  ['inventors-south-tigris', 'Inventors of the South Tigris', '⚙️', 'Inventos medievales entre libros, talleres y mecenas', 1, 4, 60, 90, 'hard', 'points'],

  // ---------------------------------------------------------------------------
  // Aventuras, campañas y mazmorras
  // ---------------------------------------------------------------------------
  ['descent-journeys', 'Descent: Journeys in the Dark', '🕳️', 'Héroes contra un señor oscuro que juega con el otro bando', 1, 5, 120, 180, 'hard', 'teams'],
  ['heroquest', 'HeroQuest', '🧙', 'El clásico de los ochenta: cuatro héroes y un maestro de mazmorra', 2, 5, 60, 90, 'easy', 'teams'],
  ['massive-darkness', 'Massive Darkness', '🔦', 'Mazmorra a saco: monta la banda y arrasa con todo', 1, 6, 60, 120, 'medium', 'coop'],
  ['massive-darkness-2', 'Massive Darkness 2: Hellscape', '👹', 'La secuela, más limpia de reglas y con más miniaturas', 1, 6, 60, 120, 'medium', 'coop'],
  ['blackstone-fortress', 'Warhammer Quest: Blackstone Fortress', '🛸', 'Una estación alienígena que explorar entre partida y partida', 1, 5, 60, 180, 'hard', 'coop'],
  ['warhammer-quest-silver-tower', 'Warhammer Quest: Silver Tower', '🗼', 'Mazmorra caótica de habitaciones cambiantes', 1, 4, 60, 120, 'medium', 'coop'],
  ['space-hulk', 'Space Hulk', '🚀', 'Marines espaciales contra genestealers en pasillos estrechos', 2, 2, 60, 90, 'medium', 'win'],
  ['kingdom-death-monster', 'Kingdom Death: Monster', '💀', 'Supervivencia brutal: cada monstruo cazado deja cicatrices', 1, 4, 60, 180, 'hard', 'coop'],
  ['oathsworn', 'Oathsworn: Into the Deepwood', '🐺', 'Campaña narrativa con combates de mazo y libro ilustrado', 1, 4, 90, 150, 'hard', 'coop'],
  ['sleeping-gods', 'Sleeping Gods', '⛵', 'Un barco perdido en un atlas ilustrado, capítulo a capítulo', 1, 4, 60, 120, 'hard', 'coop'],
  ['sleeping-gods-distant-skies', 'Sleeping Gods: Distant Skies', '🪂', 'La secuela independiente: otro atlas, la misma tripulación', 1, 4, 60, 120, 'hard', 'coop'],
  ['tainted-grail', 'Tainted Grail: The Fall of Avalon', '🌫️', 'Una Ávalon agonizante, con menús de decisiones y menhires que apagar', 1, 4, 60, 180, 'hard', 'coop'],
  ['etherfields', 'Etherfields', '🌙', 'Campaña onírica: cada sueño cambia las reglas', 1, 4, 60, 180, 'hard', 'coop'],
  ['middara', 'Middara: Unintentional Malum', '📖', 'Rol táctico en caja: mil páginas de historia y combate en rejilla', 1, 4, 90, 180, 'hard', 'coop'],
  ['iss-vanguard', 'ISS Vanguard', '🛰️', 'Una nave de exploración con secciones, tripulación y ciencia', 1, 4, 90, 150, 'hard', 'coop'],
  ['cloudspire', 'Cloudspire', '🗼', 'Torres, oleadas y facciones: un tower defense de mesa', 1, 4, 90, 180, 'hard', 'teams'],
  ['hoplomachus-victorum', 'Hoplomachus: Victorum', '🏟️', 'Gladiadores en campaña por un mapa, en solitario o en equipo', 1, 4, 60, 120, 'hard', 'coop'],
  ['kingdom-rush', 'Kingdom Rush: Rift in Time', '🏹', 'El videojuego de torres, con manipulación del tiempo', 1, 4, 60, 90, 'medium', 'coop'],
  ['earthborne-rangers', 'Earthborne Rangers', '🌲', 'Explora un valle vivo con un mazo que tú mismo construyes', 1, 4, 60, 120, 'hard', 'coop'],
  ['elden-ring-board-game', 'Elden Ring: The Board Game', '🗡️', 'Muere, aprende el patrón y vuelve a intentarlo, sobre la mesa', 1, 4, 60, 120, 'hard', 'coop'],
  ['bloodborne-board-game', 'Bloodborne: The Board Game', '🩸', 'Yharnam en campaña: cazadores, sangre y prisas', 1, 4, 60, 90, 'hard', 'coop'],
  ['frostpunk', 'Frostpunk: The Board Game', '🥶', 'Una ciudad helada y decisiones morales que se pagan caras', 1, 4, 60, 150, 'hard', 'coop'],
  ['this-war-of-mine', 'This War of Mine: The Board Game', '🥫', 'Civiles atrapados en una ciudad sitiada: sobrevivir cuesta', 1, 6, 45, 120, 'hard', 'coop'],
  ['robinson-crusoe', 'Robinson Crusoe: Adventures on the Cursed Island', '🏝️', 'Náufragos con demasiado que hacer y muy poco tiempo', 1, 4, 60, 120, 'hard', 'coop'],

  // ---------------------------------------------------------------------------
  // Terror, misterio y cooperativos
  // ---------------------------------------------------------------------------
  ['pandemic', 'Pandemic', '🦠', 'Cuatro brotes por el mundo y un equipo que llega tarde a todo', 2, 4, 45, 45, 'medium', 'coop'],
  ['pandemic-legacy-2', 'Pandemic Legacy: Season 2', '🧫', 'Setenta años después: quedan estaciones y muy poco suministro', 2, 4, 60, 60, 'hard', 'coop'],
  ['pandemic-legacy-0', 'Pandemic Legacy: Season 0', '🕵️‍♀️', 'Guerra Fría: espías, identidades falsas y un virus', 2, 4, 60, 60, 'hard', 'coop'],
  ['forbidden-island', 'Forbidden Island', '🗺️', 'La isla se hunde bajo vuestros pies: coged los tesoros y volad', 2, 4, 30, 30, 'easy', 'coop'],
  ['forbidden-desert', 'Forbidden Desert', '🌵', 'Sed, tormenta de arena y una nave que hay que montar', 2, 5, 45, 45, 'easy', 'coop'],
  ['forbidden-sky', 'Forbidden Sky', '⛈️', 'Una plataforma en la tormenta y un circuito eléctrico de verdad', 2, 5, 60, 60, 'medium', 'coop'],
  ['horrified', 'Horrified', '🧟', 'Los monstruos clásicos de la Universal, todos a la vez', 1, 5, 60, 60, 'easy', 'coop'],
  ['horrified-american', 'Horrified: American Monsters', '👣', 'Bigfoot, el Chupacabras y compañía por carreteras secundarias', 1, 5, 60, 60, 'easy', 'coop'],
  ['horrified-greek', 'Horrified: Greek Monsters', '🐍', 'Medusa, el Minotauro y las Sirenas en el mismo tablero', 1, 5, 60, 60, 'easy', 'coop'],
  ['arkham-horror', 'Arkham Horror', '🔮', 'La ciudad de Lovecraft y unos investigadores que van justos', 1, 6, 120, 180, 'hard', 'coop'],
  ['eldritch-horror', 'Eldritch Horror', '👁️', 'Arkham Horror a escala mundial y con menos reglas', 1, 8, 120, 240, 'hard', 'coop'],
  ['mansions-of-madness', 'Mansions of Madness: Second Edition', '🏚️', 'Mansión encantada con una app que hace de guardián', 1, 5, 120, 180, 'hard', 'coop'],
  ['elder-sign', 'Elder Sign', '🎲', 'El Arkham de bolsillo: dados contra los Primigenios', 1, 8, 60, 90, 'easy', 'coop'],
  ['cthulhu-wars', 'Cthulhu Wars', '🦑', 'Facciones primigenias peleando por el mundo con miniaturas enormes', 2, 4, 90, 120, 'hard', 'points'],
  ['zombicide', 'Zombicide (2ª edición)', '🧟‍♂️', 'Supervivientes, ruido y hordas que crecen cuando disparas', 1, 6, 60, 60, 'easy', 'coop'],
  ['zombicide-black-plague', 'Zombicide: Black Plague', '⚰️', 'El mismo Zombicide, pero medieval y con magia', 1, 6, 60, 60, 'medium', 'coop'],
  ['zombicide-green-horde', 'Zombicide: Green Horde', '🧌', 'Orcos zombis y una horda que se acumula fuera del tablero', 1, 6, 60, 60, 'medium', 'coop'],
  ['betrayal-house-hill', 'Betrayal at House on the Hill', '🏠', 'Exploráis juntos hasta que uno de vosotros traiciona al grupo', 3, 6, 60, 60, 'medium', 'teams'],
  ['betrayal-legacy', 'Betrayal Legacy', '📜', 'Trece capítulos de la misma casa y de vuestras familias', 3, 5, 60, 90, 'medium', 'teams'],
  ['mysterium', 'Mysterium', '👻', 'Un fantasma reparte sueños ilustrados y no puede hablar', 2, 7, 42, 42, 'easy', 'coop'],
  ['mysterium-park', 'Mysterium Park', '🎡', 'El mismo fantasma, en una feria y en media hora', 2, 6, 30, 30, 'easy', 'coop'],
  ['nemesis-lockdown', 'Nemesis: Lockdown', '🔒', 'La misma pesadilla, en una base marciana con energía y ascensores', 1, 5, 90, 180, 'hard', 'teams'],
  ['the-loop', 'The Loop', '⏳', 'Un doctor que viaja en el tiempo y se clona sin parar', 1, 4, 45, 60, 'medium', 'coop'],
  ['spirit-island-jagged-earth', 'Spirit Island: Jagged Earth', '🌏', 'La gran expansión: espíritus rarísimos y adversarios más duros', 1, 6, 90, 180, 'hard', 'coop'],
  ['aeons-end', "Aeon's End", '🌀', 'Deckbuilding sin barajar: el orden de tu mazo es información', 1, 4, 60, 60, 'medium', 'coop'],
  ['aeons-end-legacy', "Aeon's End: Legacy", '🗝️', 'Campaña: tu mago se construye carta a carta a lo largo de las partidas', 1, 4, 60, 90, 'hard', 'coop'],
  ['aeons-end-war-eternal', "Aeon's End: War Eternal", '⚡', 'Caja independiente: nuevos némesis y magos para la misma guerra', 1, 4, 60, 60, 'medium', 'coop'],
  ['big-book-of-madness', 'The Big Book of Madness', '📕', 'Aprendices que han abierto el libro que no debían', 2, 5, 60, 90, 'medium', 'coop'],
  ['lotr-journeys', 'The Lord of the Rings: Journeys in Middle-earth', '🧝‍♂️', 'La Tierra Media guiada por una app, campaña incluida', 1, 5, 60, 120, 'medium', 'coop'],
  ['lotr-lcg', 'The Lord of the Rings: The Card Game', '💍', 'Juego de cartas cooperativo con mazos que te montas tú', 1, 4, 30, 90, 'hard', 'coop'],
  ['harry-potter-hogwarts-battle', 'Harry Potter: Hogwarts Battle', '🦉', 'Deckbuilding cooperativo, un libro por año de Hogwarts', 2, 4, 30, 60, 'easy', 'coop'],
  ['harry-potter-death-eaters', 'Harry Potter: Death Eaters Rising', '⚡', 'Dados y mortífagos amenazando los lugares del mundo mágico', 2, 4, 45, 60, 'easy', 'coop'],

  // ---------------------------------------------------------------------------
  // Conflicto, control de área y 4X
  // ---------------------------------------------------------------------------
  ['game-of-thrones', 'A Game of Thrones: The Board Game', '🐺', 'Órdenes ocultas y pactos que duran justo hasta que dejan de convenir', 3, 6, 120, 240, 'hard', 'win'],
  ['star-wars-imperial-assault', 'Star Wars: Imperial Assault', '🤖', 'Campaña táctica: rebeldes contra un jugador imperial', 1, 5, 60, 120, 'hard', 'teams'],
  ['star-wars-outer-rim', 'Star Wars: Outer Rim', '🛸', 'Contrabandistas y cazarrecompensas por el Borde Exterior', 1, 4, 120, 180, 'medium', 'points'],
  ['star-wars-deckbuilding', 'Star Wars: The Deckbuilding Game', '⚔️', 'Duelo de mazos entre el Imperio y la Rebelión, en media hora', 2, 2, 20, 40, 'medium', 'win'],
  ['kemet', 'Kemet', '🔺', 'Egipto mitológico: pelear es obligatorio para puntuar', 2, 5, 90, 120, 'hard', 'points'],
  ['cyclades', 'Cyclades', '🔱', 'Subastas por el favor de los dioses griegos', 2, 5, 60, 90, 'medium', 'points'],
  ['inis', 'Inis', '🍀', 'Cartas que rotan: tres formas de ganar y todas cuestan sangre', 2, 4, 60, 90, 'hard', 'points'],
  ['ankh-gods-egypt', 'Ankh: Gods of Egypt', '🪶', 'Dioses egipcios que se fusionan cuando el panteón se queda corto', 2, 5, 90, 90, 'hard', 'points'],
  ['rising-sun', 'Rising Sun', '⛩️', 'Japón mitológico: se negocia antes de cada guerra, y se puede mentir', 3, 5, 90, 120, 'hard', 'points'],
  ['blood-rage', 'Blood Rage', '🪓', 'Vikingos en el Ragnarök: morir bien puntúa más que sobrevivir', 2, 4, 60, 90, 'medium', 'points'],
  ['chaos-in-the-old-world', 'Chaos in the Old World', '👺', 'Cuatro dioses del Caos corrompiendo el Viejo Mundo, cada uno a su manera', 3, 4, 60, 120, 'hard', 'points'],
  ['lords-of-hellas', 'Lords of Hellas', '🏛️', 'Grecia con monstruos, monumentos y héroes que corren por el mapa', 1, 4, 60, 90, 'medium', 'win'],
  ['blood-bowl', 'Blood Bowl', '🏈', 'Fútbol americano fantástico donde matar al rival es táctica', 2, 2, 60, 120, 'medium', 'points'],
  ['root-riverfolk', 'Root: The Riverfolk Expansion', '🦦', 'Nutrias mercaderes y lagartos fanáticos para el bosque', 2, 6, 60, 90, 'hard', 'points'],
  ['vast-crystal-caverns', 'Vast: The Crystal Caverns', '💎', 'Caballero, dragón, goblins y hasta la propia cueva, con reglas propias', 1, 5, 60, 120, 'hard', 'win'],
  ['oath', 'Oath', '🏵️', 'Crónica de un imperio: cada partida deja el mundo cambiado para la siguiente', 1, 6, 45, 180, 'hard', 'win'],
  ['pax-renaissance', 'Pax Renaissance', '🎭', 'Banqueros renacentistas comprando reinos y religiones', 1, 4, 60, 120, 'hard', 'points'],
  ['john-company', 'John Company: Second Edition', '🍵', 'La Compañía de las Indias: los cargos se reparten discutiendo', 1, 6, 120, 240, 'hard', 'points'],
  ['risk', 'Risk', '🌍', 'Conquistar el mundo a dados, discutiendo en Kamchatka', 2, 6, 120, 180, 'medium', 'win'],
  ['axis-allies', 'Axis & Allies', '✈️', 'La Segunda Guerra Mundial entera, con presupuesto y producción', 2, 5, 180, 240, 'hard', 'win'],
  ['memoir-44', "Memoir '44", '🪖', 'Escenarios de la Segunda Guerra Mundial con cartas de órdenes', 2, 2, 30, 60, 'easy', 'win'],
  ['memoir-44-overlord', "Memoir '44: Overlord", '🎖️', 'El mismo sistema en dos tableros, con mandos y equipos', 4, 8, 90, 180, 'medium', 'teams'],
  ['commands-colors-ancients', 'Commands & Colors: Ancients', '🏺', 'Roma y Cartago con el mismo motor de órdenes por sectores', 2, 2, 60, 90, 'medium', 'win'],
  ['commands-colors-napoleonics', 'Commands & Colors: Napoleonics', '🎩', 'Napoleón, columnas y cuadros, con bloques de madera', 2, 2, 60, 120, 'medium', 'win'],
  ['sekigahara', 'Sekigahara: The Unification of Japan', '🏯', 'Bloques ocultos y lealtades que solo se revelan al combatir', 2, 2, 180, 180, 'hard', 'points'],
  ['paths-of-glory', 'Paths of Glory', '🥀', 'La Primera Guerra Mundial completa, carta a carta', 2, 2, 240, 360, 'hard', 'win'],
  ['combat-commander-europe', 'Combat Commander: Europe', '💣', 'Escaramuzas de infantería donde las cartas llevan el caos', 2, 2, 60, 180, 'hard', 'points'],
  ['advanced-squad-leader', 'Advanced Squad Leader', '📕', 'El wargame táctico de referencia, con su reglamento de tomo', 2, 2, 120, 480, 'hard', 'win'],
  ['undaunted-normandy', 'Undaunted: Normandy', '🪂', 'Normandía con deckbuilding: tus bajas salen de tu mazo', 2, 2, 45, 60, 'medium', 'win'],
  ['undaunted-north-africa', 'Undaunted: North Africa', '🏜️', 'La misma guerra de mazos, con vehículos y desierto', 2, 2, 45, 60, 'medium', 'win'],
  ['undaunted-stalingrad', 'Undaunted: Stalingrad', '🧊', 'Campaña ramificada: las bajas se arrastran de escenario en escenario', 2, 2, 45, 60, 'hard', 'win'],
  ['unmatched-battle-legends', 'Unmatched: Battle of Legends', '🥊', 'Duelos asimétricos: Sherlock contra Drácula, y funciona', 2, 4, 20, 40, 'easy', 'win'],
  ['unmatched-cobble-fog', 'Unmatched: Cobble & Fog', '🌫️', 'Londres victoriano: Invisible, Jekyll, Van Helsing y Watson', 2, 4, 20, 40, 'easy', 'win'],
  ['unmatched-jurassic-park', 'Unmatched: Jurassic Park', '🦖', 'Doctora Sattler contra un T-Rex, con las mismas reglas de siempre', 2, 4, 20, 40, 'easy', 'win'],
  ['unmatched-adventures', 'Unmatched: Adventures', '🗿', 'La versión cooperativa: los héroes contra el tablero', 1, 4, 30, 60, 'medium', 'coop'],
  ['dice-throne', 'Dice Throne', '🎯', 'Duelo de dados: cada héroe tiene su propia hoja de combos', 2, 6, 20, 40, 'easy', 'win'],
  ['dice-throne-adventures', 'Dice Throne Adventures', '🗺️', 'Los mismos héroes, ahora cooperando en una campaña', 1, 4, 60, 120, 'medium', 'coop'],
  ['exceed', 'Exceed', '👊', 'Juegos de lucha en cartas: distancia, presión y castigo', 2, 2, 20, 30, 'medium', 'win'],
  ['battlecon', 'BattleCON: War of Indines', '🥋', 'Duelo de estilo y ataque elegidos a la vez, sin azar', 2, 2, 30, 45, 'hard', 'win'],
  ['summoner-wars', 'Summoner Wars', '🧙‍♀️', 'Ajedrez con cartas: invoca, avanza y tumba al invocador rival', 2, 2, 30, 60, 'medium', 'win'],
  ['disney-villainous', 'Disney Villainous', '🍎', 'Cada villano gana a su manera, y estorba a los demás', 2, 6, 40, 60, 'medium', 'win'],
  ['marvel-villainous', 'Marvel Villainous', '💜', 'Thanos, Ultrón y compañía contra sus propios héroes', 2, 4, 40, 80, 'medium', 'win'],
  ['star-wars-villainous', 'Star Wars Villainous', '🖤', 'El lado oscuro con la misma fórmula asimétrica', 2, 4, 40, 80, 'medium', 'win'],

  // ---------------------------------------------------------------------------
  // Familiares y de mesa camilla
  // ---------------------------------------------------------------------------
  ['dune', 'Dune', '👁️‍🗨️', 'El clásico del 79: alianzas, traiciones y profecías cumplidas', 2, 6, 120, 180, 'hard', 'win'],
  ['arnak-missing-expedition', 'Lost Ruins of Arnak: The Missing Expedition', '🧭', 'Nueva isla, nuevos guardianes y campaña para la expedición', 1, 4, 30, 120, 'hard', 'points'],
  ['clank', 'Clank!', '🐉', 'Roba en la cueva del dragón y sal antes de hacer demasiado ruido', 2, 4, 30, 60, 'medium', 'points'],
  ['clank-in-space', 'Clank! In! Space!', '🛸', 'El mismo saqueo, ahora en la nave de un señor del crimen', 2, 4, 60, 60, 'medium', 'points'],
  ['quacks-quedlinburg', 'The Quacks of Quedlinburg', '🧪', 'Saca ingredientes de la bolsa hasta que la marmita reviente', 2, 4, 45, 45, 'easy', 'points'],
  ['isle-of-cats', 'The Isle of Cats', '🐈', 'Rescata gatos en polinomios y colócalos sin dejar huecos', 1, 4, 60, 90, 'medium', 'points'],
  ['jaipur', 'Jaipur', '🐫', 'Duelo de mercaderes: vende en lotes grandes y corre por los bonus', 2, 2, 30, 30, 'easy', 'points'],
  ['tokaido', 'Tokaido', '🎌', 'Viaje sin prisa por Japón: quien va último, elige', 2, 5, 45, 45, 'easy', 'points'],
  ['takenoko', 'Takenoko', '🐼', 'Un panda glotón, un jardinero y un bambú que nunca crece a tiempo', 2, 4, 45, 45, 'easy', 'points'],
  ['machi-koro', 'Machi Koro', '🎲', 'Tira dados, cobra de tus edificios y monta el pueblo', 2, 4, 30, 30, 'easy', 'points'],
  ['machi-koro-2', 'Machi Koro 2', '🏘️', 'La secuela con mercado variable y partidas más ajustadas', 2, 5, 30, 30, 'easy', 'points'],
  ['century-spice-road', 'Century: Spice Road', '🧂', 'Cartas de especias que se transforman unas en otras', 2, 5, 30, 45, 'easy', 'points'],
  ['century-golem', 'Century: Golem Edition', '🧿', 'El mismo juego con cristales y gólems, mucho más bonito', 2, 5, 30, 45, 'easy', 'points'],
  ['century-eastern-wonders', 'Century: Eastern Wonders', '⛵', 'La segunda caja: se navega entre islas y se puede combinar con la primera', 2, 4, 30, 45, 'medium', 'points'],
  ['century-new-world', 'Century: A New World', '🪶', 'La tercera: colocación de trabajadores en el nuevo mundo', 2, 4, 30, 45, 'easy', 'points'],
  ['taverns-tiefenthal', 'The Taverns of Tiefenthal', '🍺', 'Deckbuilding con dados: llena la taberna y amplíala', 2, 4, 60, 70, 'medium', 'points'],
  ['quest-for-el-dorado', 'The Quest for El Dorado', '🌴', 'Carrera en la jungla con un mazo que te compras por el camino', 2, 4, 30, 60, 'easy', 'win'],
  ['sagrada', 'Sagrada', '🪟', 'Vidrieras de dados con reglas de color y tono muy estrictas', 1, 4, 30, 45, 'easy', 'points'],
  ['kingdomino', 'Kingdomino', '🀄', 'Dominó de reinos: elige loseta sabiendo que eso te da el turno', 2, 4, 15, 20, 'easy', 'points'],
  ['queendomino', 'Queendomino', '👸', 'Kingdomino con edificios, torres y dragón', 2, 4, 25, 30, 'easy', 'points'],
  ['akropolis', 'Akropolis', '🏛️', 'Ciudad griega en tres dimensiones: lo que tapas también puntúa', 2, 4, 20, 30, 'easy', 'points'],
  ['dorfromantik', 'Dorfromantik: The Board Game', '🚂', 'Losetas plácidas y una campaña que abre cajitas al cumplir metas', 1, 6, 30, 60, 'easy', 'coop'],
  ['calico', 'Calico', '🧶', 'Colcha de gatos: colores, patrones y ni un hueco desaprovechado', 1, 4, 30, 45, 'medium', 'points'],
  ['parks', 'Parks', '🏞️', 'Ruta por los parques nacionales, estación a estación', 1, 5, 30, 60, 'medium', 'points'],
  ['trails', 'Trails', '🥾', 'El hermano pequeño de Parks: media hora de senderismo', 2, 4, 20, 30, 'easy', 'points'],
  ['meadow', 'Meadow', '🦌', 'Cartas de naturaleza ilustradas y requisitos que encajar', 1, 4, 60, 90, 'medium', 'points'],
  ['verdant', 'Verdant', '🪴', 'Coloca plantas junto a la ventana con la luz que piden', 1, 5, 30, 45, 'easy', 'points'],
  ['flamecraft', 'Flamecraft', '🐲', 'Dragoncitos artesanos abasteciendo las tiendas del pueblo', 1, 5, 60, 60, 'easy', 'points'],
  ['living-forest', 'Living Forest', '🌳', 'Un bosque que arde mientras montas tu mazo de animales', 2, 4, 40, 40, 'medium', 'points'],
  ['photosynthesis', 'Photosynthesis', '🌲', 'Árboles que crecen a la luz y le hacen sombra al vecino', 2, 4, 30, 60, 'medium', 'points'],
  ['creature-comforts', 'Creature Comforts', '🦡', 'Animalitos preparando el invierno con dados comunes', 1, 5, 45, 60, 'easy', 'points'],
  ['canvas', 'Canvas', '🎨', 'Cartas transparentes que se superponen para pintar un cuadro', 1, 5, 30, 30, 'easy', 'points'],
  ['earth', 'Earth', '🌱', 'Un tapiz de plantas donde casi todo lo que hacen los demás te da algo', 1, 5, 45, 90, 'medium', 'points'],
  ['apiary', 'Apiary', '🐝', 'Abejas espaciales cuyos trabajadores hibernan al llegar a cuatro', 1, 5, 60, 90, 'hard', 'points'],
  ['everdell-farshore', 'Everdell: Farshore', '🌊', 'Everdell independiente, en el puerto y con un mercado nuevo', 1, 4, 40, 80, 'medium', 'points'],
  ['everdell-newleaf', 'Everdell: Newleaf', '🚉', 'Expansión con estación de tren, visitantes y billetes', 1, 4, 40, 80, 'medium', 'points'],
  ['the-river-wild', 'The River Wild', '🛶', 'Río abajo en canoa, con un mazo que se va afinando', 1, 4, 45, 60, 'easy', 'points'],
  ['naga-raja', 'Naga Raja', '🐍', 'Duelo de exploradores en un templo, echando fichas a la suerte', 2, 2, 30, 30, 'easy', 'points'],
  ['patchwork-doodle', 'Patchwork Doodle', '✏️', 'Patchwork con lápiz: todos dibujan la misma pieza a la vez', 1, 6, 15, 20, 'easy', 'points'],
  ['welcome-to', 'Welcome To...', '🏡', 'Urbanización de los cincuenta, con tres mazos y mucho tachón', 1, 100, 25, 45, 'easy', 'points'],
  ['welcome-to-the-moon', 'Welcome to the Moon', '🌕', 'La secuela en campaña: ocho hojas distintas y una historia', 1, 6, 25, 45, 'medium', 'points'],
  ['railroad-ink', 'Railroad Ink', '🛤️', 'Dados de vías y carreteras que todos dibujan a la vez', 1, 6, 20, 30, 'easy', 'points'],
  ['cartographers', 'Cartographers', '🗺️', 'Dibuja el mapa de la reina y cuidado con los monstruos del vecino', 1, 100, 30, 45, 'easy', 'points'],
  ['cartographers-heroes', 'Cartographers Heroes', '🛡️', 'La versión con héroes: mismo mapa, más formas de puntuar', 1, 100, 30, 45, 'easy', 'points'],
  ['next-station-london', 'Next Station: London', '🚇', 'Traza líneas de metro con lápiz sobre el plano de Londres', 1, 4, 25, 25, 'easy', 'points'],
  ['trekking-through-history', 'Trekking Through History', '⏱️', 'Viaja a episodios históricos gastando exactamente el tiempo justo', 2, 4, 30, 60, 'easy', 'points'],
  ['trekking-the-world', 'Trekking the World', '🌏', 'Ruta por destinos famosos, con souvenirs y postales', 2, 5, 30, 60, 'easy', 'points'],

  // ---------------------------------------------------------------------------
  // Investigación y escape
  // ---------------------------------------------------------------------------
  ['cluedo', 'Cluedo', '🔎', 'Fue el coronel Mostaza, en la biblioteca, con el candelabro', 2, 6, 45, 45, 'easy', 'win'],
  ['search-for-planet-x', 'The Search for Planet X', '🔭', 'Deducción astronómica: cada observación descarta un poco más', 1, 4, 60, 75, 'medium', 'points'],
  ['chronicles-of-crime', 'Chronicles of Crime', '📱', 'Escenas del crimen escaneadas con el móvil y realidad virtual', 1, 4, 60, 90, 'easy', 'coop'],
  ['chronicles-of-crime-1400', 'Chronicles of Crime: 1400', '🏰', 'La misma app, ahora en la Edad Media', 1, 4, 60, 90, 'easy', 'coop'],
  ['micromacro-crime-city', 'MicroMacro: Crime City', '🔍', 'Un mapa gigante en blanco y negro donde está todo, si lo encuentras', 1, 4, 15, 45, 'easy', 'coop'],
  ['micromacro-full-house', 'MicroMacro: Crime City – Full House', '🏙️', 'Otro mapa, otros dieciséis casos que resolver con la lupa', 1, 4, 15, 45, 'easy', 'coop'],
  ['detective-modern-crime', 'Detective: A Modern Crime Board Game', '🗄️', 'Casos con base de datos en línea y cinco días para resolverlos', 1, 5, 120, 180, 'hard', 'coop'],
  ['sherlock-holmes-consulting', 'Sherlock Holmes Consulting Detective', '🎻', 'Londres, un periódico y un cuaderno: solo se lee y se piensa', 1, 8, 60, 120, 'medium', 'coop'],
  ['unlock', 'Unlock!', '🔓', 'Escape room en cartas, con app que cronometra y da pistas', 1, 6, 60, 60, 'easy', 'coop'],
  ['exit-the-game', 'EXIT: The Game', '🚪', 'Escape room de un solo uso: hay que romper los componentes', 1, 4, 45, 90, 'medium', 'coop'],
  ['deception-murder-hong-kong', 'Deception: Murder in Hong Kong', '🔪', 'El forense da pistas y el asesino está en la mesa', 4, 12, 20, 20, 'easy', 'teams'],
  ['awkward-guests', 'Awkward Guests', '🍽️', 'Un asesinato con muchísimas pistas repartidas entre todos', 1, 6, 45, 90, 'medium', 'win'],

  // ---------------------------------------------------------------------------
  // Fiesta, palabras y deducción social
  // ---------------------------------------------------------------------------
  ['decrypto', 'Decrypto', '🔐', 'Pistas para los tuyos que el otro equipo no debe descifrar', 3, 8, 15, 45, 'medium', 'teams'],
  ['wavelength', 'Wavelength', '📻', 'Poner el dial entre «frío» y «caliente» y rezar', 2, 12, 30, 45, 'easy', 'teams'],
  ['just-one', 'Just One', '☝️', 'Todos escriben una pista y las repetidas se tachan', 3, 7, 20, 20, 'easy', 'coop'],
  ['so-clover', 'So Clover!', '🍀', 'Una pista por lado del trébol para que adivinen tus parejas', 3, 6, 30, 30, 'easy', 'coop'],
  ['concept', 'Concept', '💭', 'Explícalo señalando iconos, sin decir ni una palabra', 4, 12, 40, 40, 'easy', 'teams'],
  ['imagine', 'Imagine', '🖼️', 'Transparencias que se superponen para explicar un título', 3, 8, 30, 30, 'easy', 'points'],
  ['telestrations', 'Telestrations', '✏️', 'El teléfono escacharrado, pero dibujando', 4, 8, 30, 30, 'easy', 'points'],
  ['dixit-odyssey', 'Dixit Odyssey', '🦋', 'Más cartas oníricas y hasta doce jugadores', 3, 12, 30, 30, 'easy', 'points'],
  ['insider', 'Insider', '🧅', 'Veinte preguntas, y uno de vosotros ya sabía la respuesta', 4, 8, 15, 15, 'easy', 'teams'],
  ['the-resistance', 'The Resistance', '🚩', 'Misiones que fallan y espías que nadie consigue señalar', 5, 10, 30, 30, 'easy', 'teams'],
  ['secret-hitler', 'Secret Hitler', '🎩', 'Se aprueban leyes a ciegas y el gobierno se llena de fascistas', 5, 10, 45, 45, 'medium', 'teams'],
  ['one-night-ultimate-werewolf', 'One Night Ultimate Werewolf', '🐺', 'Una sola noche, un solo linchamiento, ninguna eliminación', 3, 10, 10, 10, 'easy', 'teams'],
  ['werewords', 'Werewords', '🗣️', 'Adivinad la palabra en cuatro minutos, con un lobo dando pistas falsas', 4, 10, 10, 10, 'easy', 'teams'],
  ['blood-on-the-clocktower', 'Blood on the Clocktower', '🔔', 'Hombres lobo donde los muertos siguen jugando y el narrador miente', 5, 20, 30, 120, 'hard', 'teams'],
  ['spyfall', 'Spyfall', '📍', 'Todos saben dónde estamos menos uno, y no puede notarse', 3, 8, 15, 15, 'easy', 'teams'],
  ['spyfall-2', 'Spyfall 2', '🕶️', 'Más localizaciones, más jugadores y hasta dos espías', 3, 12, 15, 15, 'easy', 'teams'],
  ['the-chameleon', 'The Chameleon', '🦎', 'Di una palabra que encaje sin tener ni idea del tema', 3, 8, 15, 20, 'easy', 'teams'],
  ['coup', 'Coup', '🎭', 'Dos cartas, mucha mentira y cero pruebas', 2, 6, 15, 15, 'easy', 'win'],
  ['skull', 'Skull', '💀', 'Apuesta a que levantas rosas y no la calavera', 3, 6, 15, 45, 'easy', 'win'],
  ['cockroach-poker', 'Cockroach Poker', '🪳', 'Pásale bichos al de al lado diciéndole lo que quieras', 2, 6, 20, 20, 'easy', 'lowest'],
  ['anomia', 'Anomia', '🗯️', 'Nombra algo de la categoría antes que el otro y te bloqueas', 3, 6, 20, 30, 'easy', 'points'],
  ['times-up', "Time's Up!", '⏰', 'Tres rondas, los mismos personajes y cada vez menos palabras', 4, 12, 30, 90, 'easy', 'teams'],
  ['taboo', 'Taboo', '🚫', 'Haz que lo digan sin usar ninguna de las cinco palabras prohibidas', 4, 10, 20, 60, 'easy', 'teams'],
  ['pictionary', 'Pictionary', '🖍️', 'Dibuja rápido y mal, que ya lo adivinarán', 3, 16, 40, 90, 'easy', 'teams'],
  ['scattergories', 'Scattergories', '🔤', 'Palabras con la misma letra, y las repetidas no valen', 2, 6, 30, 30, 'easy', 'points'],
  ['balderdash', 'Balderdash', '📖', 'Invéntate la definición y cuela que es la del diccionario', 2, 6, 60, 60, 'easy', 'points'],
  ['apples-to-apples', 'Apples to Apples', '🍏', 'Elige la carta que más le va a gustar a quien juzga', 4, 10, 30, 30, 'easy', 'points'],
  ['cards-against-humanity', 'Cards Against Humanity', '🃏', 'Rellenar huecos con la peor respuesta posible', 4, 20, 30, 90, 'easy', 'points'],
  ['exploding-kittens', 'Exploding Kittens', '💥', 'Ruleta rusa con gatitos y cartas para escaquearte', 2, 5, 15, 15, 'easy', 'win'],
  ['unstable-unicorns', 'Unstable Unicorns', '🦄', 'Junta siete unicornios mientras te los van reventando', 2, 8, 30, 45, 'easy', 'win'],
  ['taco-cat-goat-cheese-pizza', 'Taco Cat Goat Cheese Pizza', '🌮', 'Di la palabra, gira la carta y date de manotazos', 2, 8, 10, 10, 'easy', 'win'],
  ['dobble', 'Dobble', '⭕', 'Siempre hay un símbolo en común: cuestión de verlo antes', 2, 8, 15, 15, 'easy', 'points'],
  ['jungle-speed', 'Jungle Speed', '🪵', 'Al primero que coja el tótem, si no se lo lleva otro', 2, 8, 15, 15, 'easy', 'win'],
  ['bananagrams', 'Bananagrams', '🍌', 'Tu propio crucigrama, contrarreloj y sin turnos', 1, 8, 15, 15, 'easy', 'win'],

  // ---------------------------------------------------------------------------
  // Juegos de cartas
  // ---------------------------------------------------------------------------
  ['the-crew-planet-nine', 'The Crew: The Quest for Planet Nine', '🛰️', 'Bazas cooperativas: cincuenta misiones y casi nada que decirse', 2, 5, 20, 20, 'medium', 'coop'],
  ['the-mind', 'The Mind', '🧠', 'Bajad las cartas en orden sin hablar. Sí, así de raro', 2, 4, 15, 20, 'easy', 'coop'],
  ['hanabi', 'Hanabi', '🎆', 'Ves las cartas de los demás menos las tuyas: montad los fuegos', 2, 5, 25, 25, 'easy', 'coop'],
  ['the-game', 'The Game', '📉', 'Cuatro montones, cien cartas y prohibido decir números', 1, 5, 20, 20, 'easy', 'coop'],
  ['love-letter', 'Love Letter', '💌', 'Una carta en la mano y toda la partida en dos minutos', 2, 6, 20, 20, 'easy', 'points'],
  ['sushi-go', 'Sushi Go!', '🍣', 'Pasa la mano y quédate con el mejor plato de la cinta', 2, 5, 15, 20, 'easy', 'points'],
  ['sushi-go-party', 'Sushi Go Party!', '🍱', 'El mismo drafting con menú configurable y hasta ocho comensales', 2, 8, 20, 20, 'easy', 'points'],
  ['scout', 'Scout', '🎪', 'No se ordena la mano: o la juegas como está o robas del rival', 2, 5, 15, 20, 'easy', 'points'],
  ['sea-salt-and-paper', 'Sea Salt & Paper', '🐚', 'Papiroflexia marina: cortar la ronda pronto o arriesgarse a más', 2, 4, 30, 45, 'easy', 'points'],
  ['trio', 'Trio', '🃏', 'Encuentra los tres números iguales entre manos y mesa', 3, 6, 15, 15, 'easy', 'points'],
  ['cabo', 'Cabo', '🎴', 'Memoriza tus cartas y canta antes de que te pillen', 2, 4, 15, 30, 'easy', 'lowest'],
  ['six-nimmt', '6 Nimmt!', '🐮', 'Cuatro filas, cartas simultáneas y una sexta que te come', 2, 10, 45, 45, 'easy', 'lowest'],
  ['no-thanks', 'No Thanks!', '🙅', 'O te llevas la carta o pagas por no llevártela', 3, 7, 20, 20, 'easy', 'lowest'],
  ['for-sale', 'For Sale', '🏚️', 'Dos subastas seguidas: compra barato y vende caro, en diez minutos', 3, 6, 20, 30, 'easy', 'points'],
  ['high-society', 'High Society', '💎', 'Presume de lujo sin ser el que menos dinero conserve', 3, 5, 15, 30, 'easy', 'points'],
  ['modern-art', 'Modern Art', '🖌️', 'Cinco tipos de subasta y un mercado del arte que fijáis vosotros', 3, 5, 45, 60, 'medium', 'points'],
  ['chinatown', 'Chinatown', '🥡', 'Negociación pura: todo se puede cambiar por todo', 3, 5, 60, 90, 'medium', 'points'],
  ['bohnanza', 'Bohnanza', '🫘', 'Judías que no puedes reordenar y trueques constantes', 2, 7, 45, 45, 'easy', 'points'],
  ['fox-in-the-forest', 'The Fox in the Forest', '🦊', 'Bazas a dos donde ganar demasiadas te deja sin nada', 2, 2, 30, 30, 'easy', 'points'],
  ['fox-in-the-forest-duet', 'The Fox in the Forest Duet', '🌲', 'Las mismas bazas, ahora cooperando por el bosque', 2, 2, 30, 30, 'easy', 'coop'],
  ['lost-cities', 'Lost Cities', '⛏️', 'Expediciones que no compensa empezar si no vas a llegar lejos', 2, 2, 30, 30, 'easy', 'points'],
  ['schotten-totten', 'Schotten Totten', '🪨', 'Nueve mojones y la mejor mano de tres cartas en cada uno', 2, 2, 20, 20, 'easy', 'win'],
  ['battle-line', 'Battle Line', '⚔️', 'El mismo duelo de mojones, con tácticas y ambientación antigua', 2, 2, 30, 30, 'medium', 'win'],
  ['air-land-sea', 'Air, Land & Sea', '🛩️', 'Dieciocho cartas, tres frentes y la opción de retirarse a tiempo', 2, 2, 15, 20, 'easy', 'points'],
  ['radlands', 'Radlands', '☢️', 'Postapocalíptico a dos: protege tus tres campamentos', 2, 2, 30, 45, 'medium', 'win'],
  ['mindbug', 'Mindbug', '🧠', 'Diez cartas rotísimas y el rival puede robarte la que juegues', 2, 2, 15, 20, 'easy', 'win'],
  ['mindbug-beyond-eternity', 'Mindbug: Beyond Eternity', '♾️', 'Caja independiente con criaturas y efectos nuevos', 2, 2, 15, 20, 'easy', 'win'],
  ['phase-10', 'Phase 10', '🔟', 'Diez fases en orden y un rummy que se alarga', 2, 6, 45, 60, 'easy', 'win'],
  ['skip-bo', 'Skip-Bo', '🔢', 'Vacía tu montón antes que nadie, carta a carta', 2, 6, 30, 45, 'easy', 'win'],

  // ---------------------------------------------------------------------------
  // Construcción de mazos y juegos de coleccionismo
  // ---------------------------------------------------------------------------
  ['dominion-intrigue', 'Dominion: Intrigue', '🗝️', 'Caja independiente: cartas con elección y ataques molestos', 2, 4, 30, 30, 'medium', 'points'],
  ['dominion-seaside', 'Dominion: Seaside', '⚓', 'Expansión de duración: acciones que siguen activas al turno siguiente', 2, 4, 30, 30, 'medium', 'points'],
  ['star-realms', 'Star Realms', '🌟', 'Deckbuilding de combate a dos, en veinte minutos y por poco dinero', 2, 2, 20, 20, 'easy', 'win'],
  ['hero-realms', 'Hero Realms', '🛡️', 'Star Realms en fantasía, con personajes y campañas', 2, 4, 20, 30, 'easy', 'win'],
  ['ascension', 'Ascension', '🌅', 'Deckbuilding clásico: centro de mesa, runas y poder', 1, 4, 30, 30, 'easy', 'points'],
  ['legendary-marvel', 'Legendary: A Marvel Deck Building Game', '🦸', 'Héroes Marvel contra un villano con su plan', 1, 5, 45, 60, 'medium', 'coop'],
  ['marvel-united', 'Marvel United', '🦹', 'Cooperativo ligero de miniaturas: cada héroe extiende la línea del turno', 1, 4, 40, 40, 'easy', 'coop'],
  ['marvel-united-xmen', 'Marvel United: X-Men', '❌', 'La caja mutante: mismo juego, la Patrulla X al completo', 1, 4, 40, 40, 'easy', 'coop'],
  ['dice-forge', 'Dice Forge', '⚒️', 'Deckbuilding con caras de dado que se cambian físicamente', 2, 4, 45, 45, 'easy', 'points'],
  ['quarriors', 'Quarriors!', '👾', 'Dicebuilding: compras dados de una bolsa y los tiras al momento', 2, 4, 30, 30, 'easy', 'points'],
  ['marvel-dice-masters', 'Marvel Dice Masters', '🎲', 'Duelo de dados coleccionables con personajes de cómic', 2, 2, 30, 45, 'medium', 'win'],
  ['netrunner', 'Android: Netrunner', '💻', 'Corporación contra hacker: información oculta y faroles caros', 2, 2, 45, 45, 'hard', 'win'],
  ['magic-the-gathering', 'Magic: The Gathering', '✨', 'El primer juego de cartas coleccionables, y sigue mandando', 2, 2, 20, 60, 'hard', 'win'],
  ['pokemon-tcg', 'Pokémon Trading Card Game', '⚡', 'Seis premios, banquillo y evoluciones sobre la mesa', 2, 2, 20, 30, 'medium', 'win'],
  ['yugioh-tcg', 'Yu-Gi-Oh! Trading Card Game', '🐉', 'Invocaciones encadenadas y turnos que duran lo suyo', 2, 2, 20, 40, 'hard', 'win'],
  ['disney-lorcana', 'Disney Lorcana', '🔮', 'Personajes Disney compitiendo por veinte puntos de lore', 2, 2, 20, 40, 'medium', 'win'],
  ['flesh-and-blood', 'Flesh and Blood', '🗡️', 'Cartas de combate cuerpo a cuerpo: cada carta es recurso o ataque', 2, 2, 20, 40, 'hard', 'win'],
  ['keyforge', 'KeyForge', '🔑', 'Mazos únicos que no se construyen: se abren y se juegan', 2, 2, 30, 45, 'medium', 'win'],
  ['ashes-reborn', 'Ashes Reborn', '🔥', 'Duelo de magos con dados y un mazo que se recicla solo', 2, 2, 40, 60, 'hard', 'win'],

  // ---------------------------------------------------------------------------
  // Abstractos y duelos a dos
  // ---------------------------------------------------------------------------
  ['chess', 'Ajedrez', '♟️', 'El juego del que salen todos los demás', 2, 2, 30, 60, 'hard', 'win'],
  ['go', 'Go', '⚫', 'Reglas de una página y una vida entera para aprenderlo', 2, 2, 30, 180, 'hard', 'win'],
  ['backgammon', 'Backgammon', '🎲', 'Dados y carrera, con el cubo de doblar como veneno', 2, 2, 15, 30, 'medium', 'win'],
  ['hive', 'Hive', '🐝', 'Ajedrez de bichos sin tablero: la colmena no se puede partir', 2, 2, 20, 20, 'medium', 'win'],
  ['onitama', 'Onitama', '🥋', 'Cinco cartas de movimiento que van pasando de un lado a otro', 2, 2, 15, 20, 'easy', 'win'],
  ['santorini', 'Santorini', '🏛️', 'Construye, sube y llega al tercer piso antes que el otro', 2, 4, 20, 20, 'easy', 'win'],
  ['tak', 'Tak', '🪵', 'Construye un camino de lado a lado con piedras y muros', 2, 2, 30, 60, 'medium', 'win'],
  ['quarto', 'Quarto', '🔲', 'Tú eliges la pieza que juega el rival: ahí está todo', 2, 2, 20, 20, 'easy', 'win'],
  ['quoridor', 'Quoridor', '🧱', 'Llega al otro lado poniendo vallas que estorben, no que encierren', 2, 4, 15, 15, 'easy', 'win'],
  ['splendor-duel', 'Splendor Duel', '💠', 'Splendor a dos, con tablero de fichas y tres formas de ganar', 2, 2, 30, 30, 'medium', 'points'],
  ['azul-summer-pavilion', 'Azul: Summer Pavilion', '☀️', 'Azul con estrellas y comodines: la tercera y más amable', 2, 4, 30, 45, 'medium', 'points'],
  ['azul-sintra', 'Azul: Stained Glass of Sintra', '🪟', 'Azul con vidrieras y paneles que se van rompiendo', 2, 4, 30, 45, 'medium', 'points'],
  ['azul-queens-garden', "Azul: Queen's Garden", '🌷', 'El Azul más duro: casi todo puntúa y casi nada cabe', 2, 4, 45, 60, 'hard', 'points'],
]
